## YAML Override template
## original/file.tpl: override/file.tpl
---
system/Search/Resources/view/search_block_search.tpl: themes/Andreas08/Resources/view/modules/Search/search_block_search.tpl
system/Blocks/Resources/view/blocks_block_extmenu_topnav.tpl: themes/Andreas08/Resources/view/modules/Blocks/blocks_block_extmenu_topnav.tpl