<?php
/**
 * Routes.
 *
 * @copyright Zikula contributors (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula contributors <support@zikula.org>.
 * @link http://www.zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.0 (https://modulestudio.de).
 */

namespace Zikula\RoutesModule\Helper;

use Zikula\RoutesModule\Helper\Base\AbstractEntityDisplayHelper;

/**
 * Entity display helper implementation class.
 */
class EntityDisplayHelper extends AbstractEntityDisplayHelper
{
    // feel free to extend the entity display helper here
}
