## YAML Override template
## original/file.tpl: override/file.tpl
---
system/SearchModule/Resources/views/search_block_search.tpl: themes/Andreas08Theme/Resources/views/modules/Search/search_block_search.tpl
system/BlocksModule/Resources/views/blocks_block_extmenu_topnav.tpl: themes/Andreas08Theme/Resources/views/modules/Blocks/blocks_block_extmenu_topnav.tpl