services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $mailLoggingEnabled: '%enable_mail_logging%'

    Zikula\AdminBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\AdminBundle\Helper\:
        resource: '../../Helper/*'
        lazy: true
