services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\AdminBundle\ZikulaAdminBundle'

    Zikula\AdminBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\AdminBundle\Helper\:
        resource: '../../Helper/*'
        lazy: true
