services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $extension: '@Zikula\BlocksModule\ZikulaBlocksModule'

    Zikula\BlocksModule\Tests\Api\Fixture\:
        resource: '../../Tests/Api/Fixture/*'

    Zikula\BlocksModule\Tests\Collector\Fixture\:
        resource: '../../Tests/Collector/Fixture/*'

    Zikula\BlocksModule\Tests\Helper\Fixture\:
        resource: '../../Tests/Helper/Fixture/*'
