<?php
/**
 * Routes.
 *
 * @copyright Zikula contributors (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula contributors <support@zikula.org>.
 * @link http://www.zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace Zikula\RoutesModule\Api;

use Zikula\RoutesModule\Api\Base\CacheApi as BaseCacheApi;

/**
 * Cache api implementation class.
 */
class CacheApi extends BaseCacheApi
{
    // feel free to extend the cache api here
}
