doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: 5 # any value will work (bypasses DBALException)
        types:
            utcdatetime:
                class: Zikula\Bundle\CoreBundle\Doctrine\DBAL\Type\UTCDateTimeType
    orm:
        proxy_namespace: DoctrineProxy
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/DoctrineProxy'
        default_entity_manager: default
        auto_generate_proxy_classes: true
        #naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        entity_managers:
            # the standard distribution overrides this to be true in debug, false otherwise
            default:
                auto_mapping: true
                #metadata_cache_driver: array
                #query_cache_driver: array
                #result_cache_driver: array
                mappings:
                    zikula_hookstorage:
                        type: annotation
                        prefix: Zikula\Bundle\HookBundle\Dispatcher\Storage\Doctrine\Entity
                        dir: '%kernel.project_dir%/src/Zikula/HookBundle/Dispatcher/Storage/Doctrine/Entity'
                        alias: ZikulaHookStorage # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity'
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity'
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity'
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity'
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
