liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: 'gd'
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    loaders:
        zikula_root:
            filesystem:
                data_root: "%kernel.project_dir%/public"
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"
    filter_sets:
        cache: ~
        my_thumb: # sample
            jpeg_quality: 90
            png_compression_level: 7
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
                background: { size: [124, 94], position: center, color: '#000000' }
        zkroot: # sample using zikula root
            data_loader: zikula_root
            jpeg_quality: 90
            png_compression_level: 7
            filters:
                thumbnail: { size: [100, 100], mode: inset }
        # add more filters as required for your personal application
