engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
      max-statements:
        enabled: false
      no-alert:
        enabled: false
      wrap-iife:
        enabled: false
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - HACK
      - TODO
  markdownlint:
    enabled: true
    checks:
      MD009: # trailing spaces
        enabled: false
      MD013: # line length
        enabled: false
  phan:
    enabled: true
    config:
      ignore-undeclared: true
      dead-code-detection: true
    checks:
      PhanNonClassMethodCall:
        enabled: false
      PhanTypeMismatchProperty:
        enabled: false
      PhanUnreferencedClass:
        enabled: false
      PhanUnreferencedMethod:
        enabled: false
  phpcodesniffer:
    enabled: true
    checks:
      Generic Files LineLength TooLong:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration TerminatingComment:
        enabled: false
      PSR2 Methods MethodDeclaration Underscore:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration SpaceAfterFunction:
        enabled: false
  phpmd:
    enabled: true
    checks:
      CleanCode/ElseExpression:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      CyclomaticComplexity:
        enabled: false
      Design/CouplingBetweenObjects:
        enabled: false
      Design/LongMethod:
        enabled: false
      Design/NpathComplexity:
        enabled: false
      Design/TooManyFields:
        enabled: false
      Design/TooManyPublicMethods:
        enabled: false
      Design/WeightedMethodCount:
        enabled: false
      ExcessivePublicCount:
        enabled: false
      Naming/BooleanGetMethodName:
        enabled: false
      Naming/LongVariable:
        enabled: false
      Naming/ShortMethodName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      UnusedFormalParameter:
        enabled: false
      UnusedLocalVariable:
        enabled: false

ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.md"
  - "**.php"

exclude_paths:
- "src/lib/Zikula/Bundle/WorkflowBundle/Resources/public/js/jsPlumb/"
- "*.min.js"
- "**/tests/"
- "**/vendor/"
