build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            environment:
                php: '7.2.5'
                apache2:
                    modules: ['rewrite']
            tests:
                override:
                    # disable test executions for now because system module test suites are broken
                    - true
filter:
    excluded_paths:
        - 'src/lib/Zikula/Bundle/WorkflowBundle/Resources/public/js/jsPlumb/*'
        - 'src/themes/BootstrapTheme/Resources/public/css/cerulean.css'
        - '*.min.js'
        - '*/vendor/*'
    dependency_paths:
checks:
    javascript:
        check_unnecessary_continue: true
        check_unnecessary_return: true
        check_switch_ambiguous_test: true
        check_switch_default_not_last: true
        check_switch_default_only: true
        check_too_many_arguments: true
        code_rating: true
        duplicate_code: true
        no_debugger: true
        no_else_return: true
        no_eval: true
        no_redeclare: true
        no_redeclared_const: true
        no_return_assign: true
        no_undef: true
        no_unreachable: true
        no_unused_assignment: true
        no_unused_vars: false
        no_use_before_define: true
        nsp_vulnerabilities: true
        valid_typeof: true
        var_never_initialized: true
        var_sometimes_initialized: true
    php:
        duplication: false
        unused_parameters: false
        verify_property_names: false
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        variable_existence: true
        verify_property_names: true
        uppercase_constants: true
        use_statement_alias_conflict: true
        unused_methods: true
        unused_properties: true
        unreachable_code: true
        symfony_request_injection: true
        sql_injection_vulnerabilities: true
        simplify_boolean_return: true
        security_vulnerabilities: true
        return_in_constructor: true
        return_doc_comments: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        psr2_switch_declaration: true
        psr2_class_declaration: true
        precedence_mistakes: true
        precedence_in_conditions: true
        phpunit_assertions: true
        php5_style_constructor: true
        overriding_private_members: true
        no_unnecessary_if: true
        non_commented_empty_catch_block: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        no_trailing_whitespace: true
        no_short_open_tag: true
        no_non_implemented_abstract_methods: true
        no_property_on_interface: false
        no_goto: true
        no_global_keyword: true
        no_exit: true
        no_eval: true
        no_error_suppression: true
        no_empty_statements: true
        no_debug_code: true
        no_commented_out_code: true
        missing_arguments: true
        method_calls_on_non_object: true
        instanceof_class_exists: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        fix_doc_comments: true
        encourage_single_quotes: true
        encourage_shallow_comparison: true
        encourage_postdec_operator: true
        deprecated_code_usage: true
        deadlock_detection_in_loops: true
        comparison_always_same_result: true
        code_rating: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        catch_class_exists: true
        blank_line_after_namespace_declaration: true
        avoid_usage_of_logical_operators: true
        avoid_unnecessary_concatenation: true
        avoid_todo_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_superglobals: true
        avoid_perl_style_comments: true
        avoid_fixme_comments: true
        avoid_corrupting_byteorder_marks: true
        avoid_conflicting_incrementers: true
        avoid_closing_tag: true
        avoid_aliased_php_functions: true
        avoid_duplicate_types: true
        align_assignments: false
        assignment_of_null_return: true
        argument_type_checks: true
