preset: symfony

enabled:
  - short_array_syntax
disabled:
  - concat_without_spaces
  - multiline_array_trailing_comma
  - single_quote
  - unalign_double_arrow
  - phpdoc_summary
  - phpdoc_no_empty_return
  - phpdoc_scalar
  - phpdoc_separation 
  - unalign_equals
  - spaces_cast
  - no_empty_lines_after_phpdocs
  - phpdoc_to_comment
  - phpdoc_align
  - empty_return
  - pre_increment
  - phpdoc_type_to_var

finder:
  exclude:
    - "src/javascript"
    - "src/lib/legacy/idn"
    - "tools"
    - "src/system/RoutesModule"
