preset: symfony
risky: true

enabled:
  - alpha_ordered_imports
  - cast_spaces
  - combine_consecutive_issets
  - combine_consecutive_unsets
  - concat_with_spaces
  - declare_strict_types
  - escape_implicit_backslashes
  - explicit_indirect_variable
  - explicit_string_variable
  - mb_str_functions
  - multiline_comment_opening_closing
  - no_null_property_initialization
  - no_php4_constructor
  - no_useless_else
  - php_unit_mock
  - php_unit_namespaced
  - php_unit_set_up_tear_down_visibility
  - random_api_migration
  - strict_comparison
  - ternary_to_null_coalescing

disabled:
  - cast_spaces
  - concat_without_spaces
  - function_declaration
  - native_constant_invocation_symfony
  - native_function_invocation_symfony
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_throw
  - php_unit_fqcn_annotation
  - phpdoc_align
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_summary
  - phpdoc_to_comment
  - pre_increment
  - single_quote
  - trailing_comma_in_multiline_array
  - unalign_double_arrow
  - unalign_equals

finder:
  not-path:
    - src/system/RoutesModule
  not-name:
    - "*BlockFilterApi.php"
