<?php
/**
 * Zikula Application Framework
 *
 * @copyright (c) Zikula Development Team
 * @link http://www.zikula.org
 * @version $Id$
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @package Zikula_System_Modules
 * @subpackage Users
 */

/**
 * Render and display the user's account panel. If he is not logged in, then redirect to the login screen.
 *
 * @return string The rendered template.
 */
function users_user_main()
{
    // Security check
    if (!UserUtil::isLoggedIn()) {
        System::redirect(ModUtil::url('Users', 'user', 'loginscreen'));
    } elseif (!SecurityUtil::checkPermission('Users::', '::', ACCESS_READ)) {
        return LogUtil::registerPermissionError();
    }

    // The API function is called.
    $accountlinks = ModUtil::apiFunc('Users', 'user', 'accountlinks');

    if ($accountlinks == false) {
        return LogUtil::registerError(__('Error! No results found.'), 404);
    }

    // Create output object
    $pnRender = Renderer::getInstance('Users', false, null, true);

    // Assign the items to the template
    $pnRender->assign('accountlinks', $accountlinks);

    // Return the output that has been generated by this function
    return $pnRender->fetch('users_user_main.htm');
}

/**
 * Display the base user form (login/lostpassword/register options).
 *
 * @return string The rendered template.
 */
function users_user_view()
{
    // If has logged in, header to index.php
    if (UserUtil::isLoggedIn()) {
        return System::redirect(System::getVar('entrypoint', 'index.php'));
    }

    // create output object
    $pnRender = Renderer::getInstance('Users');

    // other vars
    $pnRender->assign(ModUtil::getVar('Users'));

    return $pnRender->fetch('users_user_view.htm');
}

/**
 * Display the login form.
 *
 * Available Get Parameters:
 * - returnpage     (string) The encoded URL of the page to which the user is returned after a successful login.
 * - confirmtou     (int)    Whether the terms and policies need to be reconfirmed or not. 1 = reconfirm, otherwise do not reconfirm.
 * - changepassword (it)     Whether to force a change of password. 1 = force the change, otherwise do not.
 *
 * @param array $args All parameters passed to this function.
 *                    $args['confirmtou']     (int) Used as a default if the 'confirmtou' get parameter is not set.
 *                    $args['changepassword'] (int) Used as a default if the 'changepassword' get parameter is not set.
 *
 * @return string The rendered template.
 */
function users_user_loginscreen($args)
{
    // create output object
    $pnRender = Renderer::getInstance('Users');

    // we shouldn't get here if logged in already....
    if (UserUtil::isLoggedIn()) {
        return System::redirect(ModUtil::url('Users', 'user', 'main'));
    }

    // TODO C Appears to be unused If confirmed, it can be removed. ph
    //    $redirecttype = (int)FormUtil::getPassedValue('redirecttype', isset($args['redirecttype']) ? $args['redirecttype'] : 0, 'GET');
    //    if ($redirecttype == 0) {
    //        $returnurl = pnServerGetVar('HTTP_REFERER');
    //    } else {
    //        $returnurl = pnGetCurrentURI();
    //    }
    //    if (empty($returnurl)) {
    //        $returnurl = System::getBaseUrl();
    //    }

    $returnurl = FormUtil::getPassedValue('returnpage', null, 'GET');
    $confirmtou = (int)FormUtil::getPassedValue('confirmtou', isset($args['confirmtou']) ? $args['confirmtou'] : 0, 'GET');
    $changepassword = (int)FormUtil::getPassedValue('changepassword', isset($args['changepassword']) ? $args['changepassword'] : 0, 'GET');

    $passwordtext = ($changepassword == 1) ? __('Current password') : __('Password');

    // assign variables for the template
    $pnRender->assign('loginviaoption', ModUtil::getVar('Users', 'loginviaoption'));
    $pnRender->assign('seclevel', System::getVar('seclevel'));
    $pnRender->assign('allowregistration', ModUtil::getVar('Users', 'reg_allowreg'));
    $pnRender->assign('returnurl', $returnurl);
    // do we have to show a note about reconfirming the terms of use?
    if (ModUtil::available('legal') && (ModUtil::getVar('legal', 'termsofuse') || ModUtil::getVar('legal', 'privacypolicy'))) {
        $pnRender->assign('tou_active', ModUtil::getVar('legal', 'termsofuse', true));
        $pnRender->assign('pp_active',  ModUtil::getVar('legal', 'privacypolicy', true));
    } else {
        $confirmtou = 0;
    }

    // do we have to force the change of password?
    $pnRender->assign('changepassword', $changepassword);
    $pnRender->assign('confirmtou', $confirmtou);
    $pnRender->assign('passwordtext', $passwordtext);
    $pnRender->assign('use_password_strength_meter', ModUtil::getVar('Users', 'use_password_strength_meter'));

    return $pnRender->fetch('users_user_loginscreen.htm');
}

/**
 * Set an underage error message and route the user back to the first user page.
 *
 * @return bool True, and the user is redirected to the view function.
 */
function users_user_underage()
{
    LogUtil::registerError(__f('Sorry! You must be %s or over to register for a user account here.', ModUtil::getVar('Users', 'minage')));
    return System::redirect(ModUtil::url('Users', 'user', 'view'));
}

/**
 * Display the registration form.
 *
 * @return string The rendered template.
 */
function users_user_register()
{
    // If has logged in, header to index.php
    if (UserUtil::isLoggedIn()) {
        return System::redirect(System::getVar('entrypoint', 'index.php'));
    }

    $template = 'users_user_register.htm';
    // check if we've agreed to the age limit
    if (ModUtil::getVar('Users', 'minage') != 0 && !stristr(pnServerGetVar('HTTP_REFERER'), 'register')) {
        $template = 'users_user_checkage.htm';
    }

    // create output object
    $pnRender = Renderer::getInstance('Users', false);

    // other vars
    $modvars = ModUtil::getVar('Users');

    $pnRender->assign($modvars);
    $pnRender->assign('sitename', System::getVar('sitename'));
    $pnRender->assign('legal',    ModUtil::available('legal'));
    $pnRender->assign('tou_active', ModUtil::getVar('legal', 'termsofuse', true));
    $pnRender->assign('pp_active',  ModUtil::getVar('legal', 'privacypolicy', true));

    return $pnRender->fetch($template);
}

/**
 * Display the lost password form.
 *
 * @return string The rendered template.
 */
function users_user_lostpassword()
{
    // we shouldn't get here if logged in already....
    if (UserUtil::isLoggedIn()) {
        return System::redirect(ModUtil::url('Users', 'user', 'main'));
    }

    if (isset($_POST['submit']) && !SecurityUtil::confirmAuthKey('Users')) {
        return LogUtil::registerAuthidError(ModUtil::url('Users', 'user', 'lostpassword'));
    }

    // create output object
    $pnRender = Renderer::getInstance('Users');
    $pnRender->assign('allowregistration', ModUtil::getVar('Users', 'reg_allowreg'));

    return $pnRender->fetch('users_user_lostpassword.htm');
}

/**
 * Login a user.
 *
 * If the user is already logged in, then he is redirected to the main user function.
 * If a redirect URL is specified, then the user is redirected to that page upon
 * successful login.
 *
 * @return bool True on successful login, otherwise false.
 */
function users_user_login()
{
    // we shouldn't get here if logged in already....
    if (UserUtil::isLoggedIn()) {
        return System::redirect(ModUtil::url('Users', 'user', 'main'));
    }

    if (!SecurityUtil::confirmAuthKey('Users')) {
        return LogUtil::registerAuthidError(ModUtil::url('Users','user','loginscreen'));
    }

    $uname      = FormUtil::getPassedValue ('uname');
    $email      = FormUtil::getPassedValue ('email');
    $pass       = FormUtil::getPassedValue ('pass');
    $url        = FormUtil::getPassedValue ('url');
    $rememberme = FormUtil::getPassedValue ('rememberme', '');

    $userid = UserUtil::getIdFromName($uname);

    $userstatus = UserUtil::getVar('activated', $userid);
    $tryagain = false;
    $confirmtou = 0;
    $changepassword = 0;
    if (($userstatus == 2 || $userstatus == 6) && ModUtil::available('legal') && (ModUtil::getVar('legal', 'termsofuse', true) || ModUtil::getVar('legal', 'privacypolicy', true))) {
        $confirmtou = 1;
        $touaccepted = (int)FormUtil::getPassedValue('touaccepted', 0, 'GETPOST');
        if ($touaccepted<>1) {
            // user had to accept the terms of use, but didn't
            $tryagain = true;
        }
    }

    // the current password must be valid
    $pnuser_current_pass = UserUtil::getVar('pass', $userid);
    $pnuser_hash_number = UserUtil::getVar('hash_method', $userid);
    $hashmethodsarray   = ModUtil::apiFunc('Users', 'user', 'gethashmethods', array('reverse' => true));
    $passhash = hash($hashmethodsarray[$pnuser_hash_number], $pass);
    if ($passhash != $pnuser_current_pass) {
        $errormsg = __('Sorry! The current password you entered is not correct. Please correct your entry and try again.');
        $tryagain = true;
    }

    if ($userstatus == 4 || $userstatus == 6) {
        $changepassword = 1;
        $validnewpass = true;
        $newpass = FormUtil::getPassedValue('newpass', null, 'POST');
        $confirmnewpass = FormUtil::getPassedValue('confirmnewpass', null, 'POST');
        // checks if the new password is valid
        // the new password must be different of the current password
        if ($pass == $newpass && $validnewpass) {
            $errormsg = __('Sorry! The new and the current passwords must be different. Please correct your entries and try again.');
            $validnewpass = false;
        }

        // check if the new password satisfy the requirements
        $minpass = ModUtil::getVar('Users', 'minpass');
        if (!empty($newpass) && strlen($newpass) < $minpass && $validnewpass) {
            $errormsg = _fn('Your password must be at least %s character long.', 'Your password must be at least %s characters long.', $minpass, $minpass);
            $validnewpass = false;
        }

        // checks if the new password and the repeated new password are the same
        if (($newpass != $confirmnewpass) && $validnewpass) {
            $errormsg = __('Sorry! The two passwords you entered do not match. Please correct your entries and try again.');
            $validnewpass = false;
        }

        // checks if the new password and the repeated new password are the same
        if (empty($newpass)) {
            $validnewpass = false;
        }

        if (!$validnewpass) {
            // user password change is incorrect
            $tryagain = true;
        }
    }

    if ($tryagain) {
        // user had to accept the terms of use, but didn't
        if ($errormsg == '') {
            $errormsg = __('Error! Log-in was not completed. Please read the information below.');
        }
        return LogUtil::registerError($errormsg , 403, ModUtil::url('Users','user','loginscreen',
                                                                array('confirmtou' => $confirmtou,
                                                                      'changepassword' => $changepassword,
                                                                      'returnpage' => $url)));
    } else {
        if ($userstatus == 4 || $userstatus == 6) {
            // change the user's password
            $pnuser_hash_number = UserUtil::getVar('hash_method', $userid);
            $hashmethodsarray   = ModUtil::apiFunc('Users', 'user', 'gethashmethods', array('reverse' => true));
            $newpasshash = hash($hashmethodsarray[$pnuser_hash_number], $newpass);
            UserUtil::setVar('pass', $newpasshash, $userid);
            $pass = $newpass;
        }
        UserUtil::setVar('activated', 1, $userid);
    }

    $loginoption    = ModUtil::getVar('Users', 'loginviaoption');
    $login_redirect = ModUtil::getVar('Users', 'login_redirect');

    if (UserUtil::login((($loginoption==1) ? $email : $uname), $pass, $rememberme)) {
        // start login hook
        $uid = UserUtil::getVar('uid');
        ModUtil::callHooks('zikula', 'login', $uid, array('module' => 'zikula'));
        if ($login_redirect == 1) {
            // WCAG compliant login
            return System::redirect($url);
        } else {
            // meta refresh
            users_print_redirectpage(__('You are being logged-in. Please wait...'), $url);
        }
        return true;
    } else {
        LogUtil::registerError(__('Sorry! Unrecognised user name or password. Please try again.'));
        $reg_verifyemail = ModUtil::getVar('Users', 'reg_verifyemail');
        if ($reg_verifyemail == 2) {
            LogUtil::registerError(__('Notice: If you have just registered a new account then please check your e-mail and activate your account before trying to log in.'));
        }
        return System::redirect(ModUtil::url('Users','user','loginscreen', array('returnpage' => urlencode($url))));
    }
}

/**
 * Log a user out.
 *
 * The user is redirected to the entry point of the site, or to a redirect
 * page if specified in the site configuration.
 *
 * @return bool True (whether successfully logged out or not.)
 */
function users_user_logout()
{
    $login_redirect = ModUtil::getVar('Users', 'login_redirect');

    // start logout hook
    $uid = UserUtil::getVar('uid');
    ModUtil::callHooks('zikula', 'logout', $uid, array('module' => 'zikula'));
    if (UserUtil::logout()) {
        if ($login_redirect == 1) {
            // WCAG compliant logout - we redirect to index.php because
            // we might no have the permission for the recent site any longer
            return System::redirect(System::getVar('entrypoint', 'index.php'));
        } else {
            // meta refresh
            users_print_redirectpage(__('Done! You have been logged out.'));
        }
    } else {
        LogUtil::registerError(__('Error! You have not been logged out.'));
        return System::redirect(System::getVar('entrypoint', 'index.php'));
    }

    return true;
}

/**
 * Complete the process of creating a new user or new user registration from a registration request form.
 *
 * Available Post Parameters:
 * - uname         (string) The user name to store on the new user record.
 * - agreetoterms  (int)    Whether the user has agreed to the terms and policies or not.
 * - email         (string) The e-mail address to store on the new user record.
 * - pass          (string) The new password to store on the new user record.
 * - vpass         (string) A verification of the new password to store on the new user record.
 * - user_viewmail (mixed)  Not Used.
 * - reg_answer    (string) The user-entered answer to the configured registration anti-spam question.
 *
 * @return string|bool If registration is moderated, then the string rendering of a template, otherwise true on successful
 *                     registration; false on error.
 */
function users_user_finishnewuser()
{
    if (!SecurityUtil::confirmAuthKey('Users')) {
        return LogUtil::registerAuthidError(ModUtil::url('Users','user','register'));
    }

    $uname          = FormUtil::getPassedValue ('uname', null, 'POST');
    $agreetoterms   = FormUtil::getPassedValue ('agreetoterms', null, 'POST');
    $email          = FormUtil::getPassedValue ('email', null, 'POST');
    $vemail         = FormUtil::getPassedValue ('vemail', null, 'POST');
    $pass           = FormUtil::getPassedValue ('pass', null, 'POST');
    $vpass          = FormUtil::getPassedValue ('vpass', null, 'POST');
    // TODO - user_viewmail is not used anywhere in the function. Is it an old legacy field, or does it need to be processed?
    $user_viewemail = FormUtil::getPassedValue ('user_viewmail', null, 'POST');
    $reg_answer     = FormUtil::getPassedValue ('reg_answer', null, 'POST');

    if (ModUtil::getVar('Users', 'lowercaseuname', false)) {
        $uname = strtolower($uname);
    }

    // some defaults for error detection and redirection
    $msgtype = 'error';
    $redirectfunc = 'loginscreen';

    // Verify dynamic user data
    if (ModUtil::getVar('Users', 'reg_optitems') == 1) {
        $profileModule = System::getVar('profilemodule', '');
        if (!empty($profileModule) && ModUtil::available($profileModule)) {

            // any Profile module needs this function
            $checkrequired = ModUtil::apiFunc($profileModule, 'user', 'checkrequired');

            if ($checkrequired) {
                // ! %s is a comma separated list of fields that were left blank
                $message = __f('Error! One or more required fields were left blank or incomplete (%s).', $checkrequired['translatedFieldsStr']);

                return LogUtil::registerError($message, null, ModUtil::url('Users', 'user', 'register'));
            }
        }
    }

    // because index.php use $name var $name can not get correct value. [class007]
    $name         = $uname;
    $commentlimit = (int)ModUtil::getVar('Users', 'commentlimit', 0);
    $storynum     = (int)ModUtil::getVar('Users', 'storyhome', 10);
    $minpass      = (int)ModUtil::getVar('Users', 'minpass', 5);
    $user_regdate = DateUtil::getDatetime();

    // TODO: add require check for dynamics.
    $checkuser = ModUtil::apiFunc('Users', 'user', 'checkuser',
                              array('uname'        => $uname,
                                    'email'        => $email,
                                    'agreetoterms' => $agreetoterms));

    // if errorcode != 1 then return error msgs
    if ($checkuser != 1) {
        switch ($checkuser)
        {
            case -1:
                $message = __('Sorry! You have not been granted access to this module.');
                break;
            case 2:
                $message =  __('Sorry! The e-mail address you entered was incorrectly formatted or is unacceptable for other reasons. Please correct your entry and try again.');
                break;
            case 3:
                $message =  __('Error! Please click on the checkbox to accept the site\'s \'Terms of use\' and \'Privacy policy\'.');
                break;
            case 4:
                $message =  __('Sorry! The user name you entered is not acceptable. Please correct your entry and try again.');
                break;
            case 5:
                $message =  __('Sorry! The user name you entered is too long. The maximum length is 25 characters.');
                break;
            case 6:
                $message =  __('Sorry! The user name you entered is reserved and cannot be registered. Please choose another name and try again.');
                break;
            case 7:
                $message =  __('Sorry! Your user name cannot contain spaces. Please correct your entry and try again.');
                break;
            case 8:
                $message =  __('Sorry! This user name has already been registered. Please choose another name and try again.');
                break;
            case 9:
                $message =  __('Sorry! This e-mail address has already been registered, and it cannot be used again for creating another account.');
                break;
            case 11:
                $message =  __('Sorry! Your user agent is not accepted for registering an account on this site.');
                break;
            case 12:
                $message =  __('Sorry! E-mail addresses from the domain you entered are not accepted for registering an account on this site.');
                break;
            default:
                $message =  __('Sorry! You have not been granted access to this module.');
        } // switch

        return LogUtil::registerError($message, null, ModUtil::url('Users', 'user', 'register'));
    }

    if ($email !== $vemail) {
        $message = __('Sorry! You did not enter the same e-mail address in each box. Please correct your entry and try again.');
    }

    $modvars = ModUtil::getVar('Users');

    if (!$modvars['reg_verifyemail'] || $modvars['reg_verifyemail'] == 2) {
        if ((isset($pass)) && ("$pass" != "$vpass")) {
            $message = __('Error! You did not enter the same password in each password field. '
                . 'Please enter the same password once in each password field (this is required for verification).');

        } elseif (isset($pass) && (strlen($pass) < $minpass)) {
            $message =  _fn('Your password must be at least %s character long', 'Your password must be at least %s characters long', $minpass);

        } elseif (empty($pass) && !ModUtil::getVar('Users', 'reg_verifyemail')) {
            $message =  __('Error! Please enter a password.');
        }
    }

    if ($modvars['reg_question'] != '' && $modvars['reg_answer'] != '') {
        if ($reg_answer != $modvars['reg_answer']) {
            $message = __('Sorry! You gave the wrong answer to the anti-spam registration question. Please correct your entry and try again.');
        }
    }

    if (isset($message)) {
        return LogUtil::registerError($message, null, ModUtil::url('Users', 'user', 'register'));
    }

    // TODO: Clean up
    $registered = ModUtil::apiFunc('Users', 'user', 'finishnewuser',
                               array('uname'         => $uname,
                                     'pass'          => $pass,
                                     'email'         => $email,
                                     'user_regdate'  => $user_regdate,
                                     'storynum'      => $storynum,
                                     'commentlimit'  => $commentlimit));

    if (!$registered) {
        LogUtil::registerError(__('Error! The registration process failed. Please contact the site administrator.'));
    } else {
        if ((int)ModUtil::getVar('Users', 'moderation') == 1) {
            LogUtil::registerStatus(__('Done! Thanks for registering! Your application has been submitted for approval.'));
            $pnr = Renderer::getInstance('Users');
            return $pnr->fetch('users_user_registrationfinished.htm');
        } else {
            LogUtil::registerStatus(__('Done! You are now a registered user. You should receive your user '
                . 'account details (including your password) at the e-mail address you entered.'));
            if (ModUtil::getVar('Users', 'reg_verifyemail') == 2) {
                LogUtil::registerStatus(__('Please use the link in the e-mail message to activate your account.'));
            }
            return System::redirect(ModUtil::url('Users', 'user', $redirectfunc));
        }
    }

    return System::redirect(pnGetHomepageURL());
}

/**
 * Send the user a lost password.
 *
 * Available Post Parameters:
 * - uname (string) The user's user name.
 * - email (string) The user's e-mail address.
 * - code  (string) The confirmation code.
 *
 * @return bool True if successful request or expected error, false if unexpected error.
 */
function users_user_mailpasswd()
{
    if (!SecurityUtil::confirmAuthKey('Users')) {
        return LogUtil::registerAuthidError(ModUtil::url('Users', 'user', 'lostpassword'));
    }

    $uname = FormUtil::getPassedValue ('uname', null, 'POST');
    $email = FormUtil::getPassedValue ('email', null, 'POST');
    $code  = FormUtil::getPassedValue ('code',  null, 'POST');
    SessionUtil::delVar('lostpassword_uname');
    SessionUtil::delVar('lostpassword_email');
    SessionUtil::delVar('lostpassword_code');

    if (!empty($code)) {
        SessionUtil::setVar('lostpassword_code', $code);
    }
    if (!$email && !$uname) {
        LogUtil::registerError(__('Error! User name and e-mail address fields are empty.'));
        return System::redirect(ModUtil::url('Users', 'user', 'lostpassword'));
    }

    // save username and password for redisplay
    SessionUtil::setVar('lostpassword_uname', $uname);
    SessionUtil::setVar('lostpassword_email', $email);

    if (!empty($email) && !empty($uname)) {
        LogUtil::registerError(__('Error! Please enter a user name OR e-mail address, no both of them.'));
        return System::redirect(ModUtil::url('Users', 'user', 'lostpassword'));
    }

    //0=DatabaseError 1=WrongCode 2=NoSuchUsernameOrEmailAddress 3=PasswordMailed 4=ConfirmationCodeMailed
    $returncode = ModUtil::apiFunc('Users', 'user', 'mailpasswd',
                               array('uname' => $uname,
                                     'email' => $email,
                                     'code'  => $code));

    if (!empty($email)) {
        $who = $email;
    }
    if (!empty($uname)) {
        $who = $uname;
    }

    switch ($returncode)
    {
        case 0:
            $message = __('Error! Could not save your changes.');
            break;
        case 1:
            $message = __("Error! The code that you've enter is invalid.");
            break;
        case 2:
            $message = __('Sorry! Could not find any matching user account.');
            break;
        case 3:
            $message = __f('Done! Password e-mailed for %s.', $who);
            SessionUtil::delVar('lostpassword_uname');
            SessionUtil::delVar('lostpassword_email');
            SessionUtil::delVar('lostpassword_code');
            break;
        case 4:
            $message = __f('Done! The confirmation code for %s has been sent by e-mail.', $who);
            break;
        default:
            return false;
    }

    if ($returncode < 3) {
        LogUtil::registerError($message);
    } else {
        LogUtil::registerStatus($message);
    }

    switch ($returncode)
    {
        case 3:
            return System::redirect(ModUtil::url('Users', 'user', 'loginscreen'));
            break;
        default:
            return System::redirect(ModUtil::url('Users', 'user', 'lostpassword'));
    }
}

/**
 * Activate a user account.
 *
 * Available Get/Post Parameters;
 * - code (string) Confirmation/Activation code.
 *
 * @param array $args All parameters passed to this function.
 *                    $args['code'] (string) Used as a default if the get/post parameter 'code' is not set.
 *
 * @return bool True on success, otherwise false.
 */
function users_user_activation($args)
{
    $code = base64_decode(FormUtil::getPassedValue('code', (isset($args['code']) ? $args['code'] : null), 'GETPOST'));
    $code = explode('#', $code);

    if (!isset($code[0]) || !isset($code[1])) {
        return LogUtil::registerError(__('Error! Could not activate your account. Please contact the site administrator.'));
    }
    $uid = $code[0];
    $code = $code[1];

    // Get user Regdate
    $regdate = UserUtil::getVar('user_regdate', $uid);

    // Checking length in case the date has been stripped from its space in the mail.
    if (strlen($code) == 18) {
        if (!strpos($code, ' ')) {
            $code = substr($code, 0, 10) . ' ' . substr($code, -8);
        }
    }

    if (hash('md5', $regdate) == hash('md5', $code)) {
        $returncode = ModUtil::apiFunc('Users', 'user', 'activateuser',
                                   array('uid'     => $uid,
                                         'regdate' => $regdate));

        if (!$returncode) {
            return LogUtil::registerError(__('Error! Could not activate your account. Please contact the site administrator.'));
        }
        LogUtil::registerStatus(__('Done! Account activated.'));
        return System::redirect(ModUtil::url('Users', 'user', 'loginscreen'));
    } else {
        return LogUtil::registerError(__('Sorry! You entered an invalid confirmation code. Please correct your entry and try again.'));
    }
}

/**
 * Print a PostNuke-style login/logout redirect page. Internal use only, not intended to be called through the API.
 *
 * @param string $message The message to display on the redirect page.
 * @param string $url     The URL of the page to redirect to after this redirect page has been displayed.
 *
 * @access private
 *
 * @return bool True.
 */
function users_print_redirectpage($message, $url)
{
    $pnRender = Renderer::getInstance('Users');
    $url = (!isset($url) || empty($url)) ? System::getVar('entrypoint', 'index.php') : $url;

    // check the url
    if (substr($url, 0, 1) == '/') {
        // Root-relative links
        $url = 'http'.(pnServerGetVar('HTTPS')=='on' ? 's' : '').'://'.pnServerGetVar('HTTP_HOST').$url;
    } elseif (!preg_match('!^(?:http|https):\/\/!', $url)) {
        // Removing leading slashes from redirect url
        $url = preg_replace('!^/*!', '', $url);
        // Get base URL and append it to our redirect url
        $baseurl = System::getBaseUrl();
        $url = $baseurl.$url;
    }

    $pnRender->assign('ThemeSel', System::getVar('Default_Theme'));
    $pnRender->assign('url', $url);
    $pnRender->assign('message', $message);
    $pnRender->assign('stylesheet', ThemeUtil::getModuleStylesheet('Users'));
    $pnRender->assign('redirectmessage', __('If you are not automatically re-directed then please click here.'));
    $pnRender->display('users_user_redirectpage.htm');
    return true;
}

/**
 * Log into a site that is currently "off" (normal logins are not allowed).
 *
 * Allows the administrator to access the site during maintenance.
 *
 * Available Post Parameters:
 * - user       (string) The user name of the user attempting to log in.
 * - pass       (string) The password of the user attempting to log in.
 * - rememberme (int)    Whether the login session should persist.
 *
 * @return bool True.
 */
function users_user_siteofflogin()
{
    // do not process if the site is enabled
    if (!System::getVar('siteoff', false)) {
        $path = dirname(pnServerGetVar('PHP_SELF'));
        $path = str_replace('\\', '/', $path);
        return System::redirect($path . '/' . System::getVar('entrypoint', 'index.php'));
    }

    $user = FormUtil::getPassedValue('user', null, 'POST');
    $pass = FormUtil::getPassedValue('pass', null, 'POST');
    $rememberme = FormUtil::getPassedValue('rememberme', false, 'POST');

    UserUtil::login($user, $pass, $rememberme);

    if (!SecurityUtil::checkPermission('Settings::', 'SiteOff::', ACCESS_ADMIN)) {
        UserUtil::logout();
    }

    $path = dirname(pnServerGetVar('PHP_SELF'));
    $path = str_replace('\\', '/', $path);
    return System::redirect($path . '/' . System::getVar('entrypoint', 'index.php'));
}

/**
 * Display the configuration options for the users block.
 *
 * @return string The rendered template.
 */
function users_user_usersblock()
{
    $blocks = ModUtil::apiFunc('Blocks', 'user', 'getall');
    $mid = ModUtil::getIdFromName('Users');
    $found = false;
    foreach ($blocks as $block) {
        if ($block['mid'] == $mid && $block['bkey'] == 'user') {
            $found = true;
            break;
        }
    }

    if (!$found) {
        return LogUtil::registerPermissionError();
    }

    $pnRender = Renderer::getInstance('Users');
    $pnRender->assign(UserUtil::getVars(UserUtil::getVar('uid')));
    return $pnRender->fetch('users_user_usersblock.htm');
}

/**
 * Update the custom users block.
 *
 * Available Post Parameters:
 * - ublockon (int)   Whether the block is displayed or not.
 * - ublock   (mixed) ?.
 *
 * @return bool True on success, otherwise false.
 */
function users_user_updateusersblock()
{
    if (!UserUtil::isLoggedIn()) {
        return LogUtil::registerPermissionError();
    }

    $blocks = ModUtil::apiFunc('Blocks', 'user', 'getall');
    $mid = ModUtil::getIdFromName('Users');
    $found = false;
    foreach ($blocks as $block) {
        if ($block['mid'] == $mid && $block['bkey'] == 'user') {
            $found = true;
            break;
        }
    }

    if (!$found) {
        return LogUtil::registerPermissionError();
    }

    $uid = UserUtil::getVar('uid');
    $ublockon = (bool)FormUtil::getPassedValue('ublockon', false, 'POST');
    $ublock = (string)FormUtil::getPassedValue('ublock', '', 'POST');

    UserUtil::setVar('ublockon', $ublockon);
    UserUtil::setVar('ublock', $ublock);

    LogUtil::registerStatus(__('Done! Saved custom block.'));
    return System::redirect(ModUtil::url('Users'));
}

/**
 * Display the change password form.
 *
 * @return string The rendered template.
 */
function Users_user_changepassword()
{
    if (!UserUtil::isLoggedIn()) {
        return LogUtil::registerPermissionError();
    }

    $changepassword = ModUtil::getVar('Users', 'changepassword', 1);
    if ($changepassword <> 1) {
        return System::redirect('Users', 'user', 'main');
    }

    // Create output object
    $pnRender = Renderer::getInstance('Users', false, null, true);

    // assign vars
    $pnRender->assign('use_password_strength_meter', ModUtil::getVar('Users', 'use_password_strength_meter'));

    // Return the output that has been generated by this function
    return $pnRender->fetch('users_user_changepassword.htm');
}

/**
 * Update the user's password.
 *
 * Available Post Parameters:
 * - oldpassword        (string) The original password.
 * - newpassword        (string) The new password to be stored for the user.
 * - newpasswordconfirm (string) Verification of the new password to be stored for the user.
 *
 * @return bool True on success, otherwise false.
 */
function Users_user_updatepassword()
{
    if (!UserUtil::isLoggedIn()) {
        return LogUtil::registerPermissionError();
    }

    if (!SecurityUtil::confirmAuthKey('Users')) {
        return LogUtil::registerAuthidError(ModUtil::url('Users', 'user', 'changepassword'));
    }

    $uservars = ModUtil::getVar('Users');
    if ($uservars['changepassword'] <> 1) {
        return System::redirect('Users', 'user', 'main');
    }

    $oldpassword        = FormUtil::getPassedValue('oldpassword', '', 'POST');
    $newpassword        = FormUtil::getPassedValue('newpassword', '', 'POST');
    $newpasswordconfirm = FormUtil::getPassedValue('newpasswordconfirm', '', 'POST');

    $uname = UserUtil::getVar('uname');
    // password existing check doesn't apply to HTTP(S) based login
    if (!isset($uservars['loginviaoption']) || $uservars['loginviaoption'] == 0) {
        $user = DBUtil::selectObjectByID('users', $uname, 'uname', null, null, null, false, 'lower');
    } else {
        $user = DBUtil::selectObjectByID('users', $uname, 'email', null, null, null, false, 'lower');
    }

    $upass = $user['pass'];
    $pnuser_hash_number = $user['hash_method'];
    $hashmethodsarray   = ModUtil::apiFunc('Users', 'user', 'gethashmethods', array('reverse' => true));

    $opass = hash($hashmethodsarray[$pnuser_hash_number], $oldpassword);

    if (empty($oldpassword) || $opass != $upass) {
        return LogUtil::registerError(__('Sorry! The password you entered is not correct. Please correct your entry and try again.'),
            null, ModUtil::url('Users', 'user', 'changepassword'));
    }

    $minpass = ModUtil::getVar('Users', 'minpass');
    if (strlen($newpassword) < $minpass) {
        return LogUtil::registerError(_fn('Your password must be at least %s character long.', 'Your password must be at least %s characters long.', $minpass, $minpass),
            null, ModUtil::url('Users', 'user', 'changepassword'));
    }

    // check if the new password and the confirmation are identical
    if ($newpassword != $newpasswordconfirm) {
        return LogUtil::registerError(__('Sorry! The two passwords you entered do not match. Please correct your entries and try again.'),
            null, ModUtil::url('Users', 'user', 'changepassword'));
    }

    // set the new password
    pnUserSetPassword($newpassword);

    LogUtil::registerStatus(__('Done! Saved your new password.'));
    return System::redirect(ModUtil::url('Users', 'user', 'main'));
}

/**
 * Display the change email address form.
 *
 * @return string The rendered template.
 */
function Users_user_changeemail()
{
    if (!UserUtil::isLoggedIn()) {
        return LogUtil::registerPermissionError();
    }

    $changeemail = ModUtil::getVar('Users', 'changeemail', 1);
    if ($changeemail <> 1) {
        return System::redirect('Users', 'user', 'main');
    }

    // Create output object
    $pnRender = Renderer::getInstance('Users', false, null, true);

    // Return the output that has been generated by this function
    return $pnRender->fetch('users_user_changeemail.htm');
}

/**
 * Update the email address.
 *
 * Available Post Parameters:
 * - newemail (string) The new e-mail address to store for the user.
 *
 * @return bool True on success, otherwise false.
 */
function Users_user_updateemail()
{
    if (!UserUtil::isLoggedIn()) {
        return LogUtil::registerPermissionError();
    }

    if (!SecurityUtil::confirmAuthKey('Users')) {
        return LogUtil::registerAuthidError(ModUtil::url('Users', 'user', 'changeemail'));
    }

    $uservars = ModUtil::getVar('Users');
    if ($uservars['changeemail'] <> 1) {
        return System::redirect('Users', 'user', 'main');
    }

    $newemail = FormUtil::getPassedValue('newemail', '', 'POST');

    $checkuser = ModUtil::apiFunc('Users', 'user', 'checkuser',
                              array('uname'        => UserUtil::getVar('uname'),
                                    'email'        => $newemail,
                                    'agreetoterms' => true));

    // check email related errors only
    if (in_array($checkuser, array(-1, 2, 9, 11, 12))) {
        switch($checkuser)
        {
            case -1:
                $message = __('Sorry! You have not been granted access to this module.');
                break;
            case 2:
                $message =  __('Sorry! The e-mail address you entered was incorrectly formatted or is unacceptable for other reasons. Please correct your entry and try again.');
                break;
            case 9:
                $message =  __('Sorry! This e-mail address has already been registered, and it cannot be used again for creating another account.');
                break;
            case 11:
                $message =  __('Sorry! Your user agent is not accepted for registering an account on this site.');
                break;
            case 12:
                $message =  __('Sorry! E-mail addresses from the domain you entered are not accepted for registering an account on this site.');
                break;
            default:
                $message =  __('Sorry! You have not been granted access to this module.');
        } // switch
        return LogUtil::registerError($message, null, ModUtil::url('Users', 'user', 'changeemail'));
    }

    // save the provisional email until confimation
    if (!ModUtil::apiFunc('Users', 'user', 'savepreemail',
                    array('newemail' => $newemail))) {
        return LogUtil::registerError(__('Error! It has not been possible to change the e-mail address.'), null, ModUtil::url('Users', 'user', 'changeemail'));
    }

    LogUtil::registerStatus(__('Done! You will receive an e-mail to your new e-mail address to confirm the change.'));
    return System::redirect(ModUtil::url('Users', 'user', 'main'));
}

/**
 * Display the form that allows the user to change the language displayed to him on the site.
 *
 * @return string The rendered template.
 */
function Users_user_changelang()
{
    if (!UserUtil::isLoggedIn()) {
        return LogUtil::registerPermissionError();
    }

    // Create output object
    $pnRender = Renderer::getInstance('Users', false);

    // Assign the languages
    $pnRender->assign('languages', ZLanguage::getInstalledLanguageNames());
    $pnRender->assign('usrlang', ZLanguage::getLanguageCode());

    // Return the output that has been generated by this function
    return $pnRender->fetch('users_user_changelang.htm');
}

/**
 * Confirm the update of the email address.
 *
 * Available Get Parameters:
 * - confirmcode (string) The confirmation code.
 *
 * @param array $args All parameters passed to this function.
 *                    $args['confirmcode'] (string) Default value for the 'confirmcode' get parameter. Allows this function to be called internally.
 *
 * @return bool True on success, otherwise false.
 */
function Users_user_confirmchemail($args)
{
    $confirmcode = FormUtil::getPassedValue('confirmcode', isset($args['confirmcode']) ? $args['confirmcode'] : null, 'GET');
    if (!UserUtil::isLoggedIn()) {
        return LogUtil::registerPermissionError();
    }

    // get user new email that is waiting for confirmation
    $preemail = ModUtil::apiFunc('Users', 'user', 'getuserpreemail');

    // the e-mail change is valid during 5 days
    $fiveDaysAgo =  time() - 5*24*60*60;

    if (!$preemail || $confirmcode != $preemail['comment'] || $preemail['dynamics'] < $fiveDaysAgo) {
        LogUtil::registerError(__('Error! Your e-mail has not been found. After your request you have five days to confirm the new e-mail address.'));
        return System::redirect(ModUtil::url('Users', 'user', 'main'));
    }

    // user and confirmation code are correct. set the new email
    UserUtil::setVar('email', $preemail['email']);

    // the preemail record is deleted
    ModUtil::apiFunc('Users', 'admin', 'deny',
                array('userid' => $preemail['tid']));

    LogUtil::registerStatus(__('Done! Changed your e-mail address.'));
    return System::redirect(ModUtil::url('Users', 'user', 'main'));
}
