<?php

/**
 * Routes.
 *
 * @copyright Zikula contributors (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula contributors <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\RoutesModule\Event;

use Zikula\RoutesModule\Event\Base\AbstractItemActionsMenuPostConfigurationEvent;

/**
 * Event implementation class for extending item actions menu.
 */
class ItemActionsMenuPostConfigurationEvent extends AbstractItemActionsMenuPostConfigurationEvent
{
    // feel free to extend the event class here
}
