nucleos_user_security:
    resource: "@NucleosUserBundle/Resources/config/routing/security.php"

nucleos_user_resetting:
    resource: "@NucleosUserBundle/Resources/config/routing/resetting.php"
    prefix: /resetting

nucleos_user_update_security:
    resource: "@NucleosUserBundle/Resources/config/routing/update_security.php"
    prefix: /credentials

nucleos_user_deletion:
    resource: "@NucleosUserBundle/Resources/config/routing/deletion.php"
    prefix: /deletion
