core:
    resource: "@CoreBundle/Resources/config/routing.xml"

hook:
    resource: "@ZikulaHookBundle/Resources/config/routing.yaml"

installer:
    resource: "@ZikulaCoreInstallerBundle/Resources/config/routing/routing.xml"

workflow_editor:
    resource: "@ZikulaWorkflowBundle/Resources/config/routing.yaml"
