services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zikula\StaticContentBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    # Controllers must be public
    Zikula\StaticContentBundle\Controller\StaticController:
        public: true
