services:
    zikula_search_module.front_controller_listener:
        class: Zikula\SearchModule\Listener\FrontControllerListener
        arguments:
          - "@router"
          - "@zikula_permissions_module.api.permission"
          - "@zikula_extensions_module.api.variable"
          - "@zikula_core.common.theme.assets_header"
          - "%installed%"
          - "@=container.hasParameter('upgrading') ? parameter('upgrading') : false"
        tags:
            - { name: kernel.event_subscriber }

    zikulasearchmodule.front_controller_listener:
        alias: zikula_search_module.front_controller_listener
        deprecated: The "%service_id%" service is deprecated since 1.4.4 and will be removed in 2.0.

    zikula_search_module.module_event_listener:
        class: Zikula\SearchModule\Listener\ModuleEventListener
        arguments:
          - "@zikula_search_module.internal.searchable_module_collector"
          - "@zikula_blocks_module.block_repository"
        tags:
            - { name: kernel.event_subscriber }

    zikulasearchmodule.module_event_listener:
        alias: zikula_search_module.module_event_listener
        deprecated: The "%service_id%" service is deprecated since 1.4.4 and will be removed in 2.0.
