services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $bundle: '@Zikula\SearchModule\ZikulaSearchModule'

    Zikula\SearchModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\SearchModule\Api\ApiInterface\SearchApiInterface: '@Zikula\SearchModule\Api\SearchApi'
    Zikula\SearchModule\Entity\RepositoryInterface\SearchResultRepositoryInterface: '@Zikula\SearchModule\Entity\Repository\SearchResultRepository'
    Zikula\SearchModule\Entity\RepositoryInterface\SearchStatRepositoryInterface: '@Zikula\SearchModule\Entity\Repository\SearchStatRepository'

    Zikula\SearchModule\Collector\SearchableModuleCollector:
        arguments:
          $searchables: !tagged_iterator zikula.searchable_module

    Zikula\SearchModule\Listener\FrontControllerListener:
        arguments:
          $headerAssetBag: '@zikula_core.common.theme.assets_header'
          $installed: '%installed%'
          $isUpgrading: "@=container.hasParameter('upgrading') ? parameter('upgrading') : false"
