services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $mailLoggingEnabled: '%enable_mail_logging%'

    Zikula\ZAuthBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\ZAuthBundle\Helper\:
        resource: '../../Helper/*'
        lazy: true

    Zikula\ZAuthBundle\Api\ApiInterface\UserCreationApiInterface: '@Zikula\ZAuthBundle\Api\UserCreationApi'
    Zikula\ZAuthBundle\Repository\AuthenticationMappingRepositoryInterface: '@Zikula\ZAuthBundle\Repository\AuthenticationMappingRepository'
    Zikula\ZAuthBundle\Repository\UserVerificationRepositoryInterface: '@Zikula\ZAuthBundle\Repository\UserVerificationRepository'
