services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\MenuBundle\ZikulaMenuBundle'

    Zikula\MenuBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\MenuBundle\Voter\RequestVoter:
        tags: ['knp_menu.voter']
