parameters:
    profile_property_prefix: 'zpmpp'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zikula\UsersBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\UsersBundle\Bundle\MetaData\UsersBundleMetaData:
        public: true

    Zikula\UsersBundle\Helper\:
        resource: '../../Helper/*'
        lazy: true

    Zikula\UsersBundle\Repository\UserAttributeRepositoryInterface: '@Zikula\UsersBundle\Repository\UserAttributeRepository'
    Zikula\UsersBundle\Repository\UserRepositoryInterface: '@Zikula\UsersBundle\Repository\UserRepository'
