services:
    zikula_categories_module.api.category:
        class: Zikula\CategoriesModule\Api\CategoryApi
        deprecated: 'The "%service_id%" service is deprecated. Use "zikula_categories_module.category_repository" instead'
        arguments:
          - "@translator.default"
          - "@doctrine.orm.entity_manager"
          - "@request_stack"
          - "@zikula_permissions_module.api.permission"
          - "@zikula_categories_module.category_processing_helper"
          - "@zikula_settings_module.locale_api"

    zikula_categories_module.api.category_permission:
        class: Zikula\CategoriesModule\Api\CategoryPermissionApi
        arguments:
          - "@zikula_permissions_module.api.permission"

    zikula_categories_module.api.category_registry:
        class: Zikula\CategoriesModule\Api\CategoryRegistryApi
        deprecated: 'The "%service_id%" service is deprecated. Use "zikula_categories_module.category_registry_repository" instead'
        arguments:
          - "@translator.default"
          - "@doctrine.orm.entity_manager"
          - "@zikula_categories_module.api.category"
