services:
    zikula_categories_module.api.category:
        class: Zikula\CategoriesModule\Api\CategoryApi
        arguments:
          - "@translator.default"
          - "@doctrine.orm.entity_manager"
          - "@request_stack"
          - "@zikula_permissions_module.api.permission"
          - "@zikula_categories_module.category_processing_helper"
          - "@zikula_categories_module.category_sorting_helper"
          - "@zikula_categories_module.relative_category_path_builder_helper"
          - "@zikula_settings_module.locale_api"

    zikula_categories_module.api.category_permission:
        class: Zikula\CategoriesModule\Api\CategoryPermissionApi
        arguments:
          - "@zikula_permissions_module.api.permission"
          - "@zikula_extensions_module.api.variable"

    zikula_categories_module.api.category_registry:
        class: Zikula\CategoriesModule\Api\CategoryRegistryApi
        arguments:
          - "@translator.default"
          - "@doctrine.orm.entity_manager"
          - "@zikula_categories_module.api.category"

    zikula_categories_module.api.user_categories:
        class: Zikula\CategoriesModule\Api\UserCategoriesApi
        arguments:
          - "@translator.default"
          - "@zikula_categories_module.api.category"
          - "@zikula_users_module.current_user"
