services:
    zikula_categories_module.category_processing_helper:
        class: Zikula\CategoriesModule\Helper\CategoryProcessingHelper
        arguments:
          - "@translator.default"
          - "@doctrine.orm.entity_manager"
          - "@kernel"
          - "@zikula_settings_module.locale_api"

    zikula_categories_module.category_sorting_helper:
        class: Zikula\CategoriesModule\Helper\CategorySortingHelper
        arguments:
          - "@request_stack"

    zikula_categories_module.copy_and_move_helper:
        class: Zikula\CategoriesModule\Helper\CopyAndMoveHelper
        arguments:
          - "@translator.default"
          - "@doctrine.orm.entity_manager"
          - "@zikula_categories_module.api.category"
          - "@zikula_categories_module.path_builder_helper"

    zikula_categories_module.hierarchy_helper:
        class: Zikula\CategoriesModule\Helper\HierarchyHelper
        arguments:
          - "@translator.default"
          - "@doctrine.orm.entity_manager"
          - "@zikula_categories_module.api.category"

    zikula_categories_module.html_tree_helper:
        class: Zikula\CategoriesModule\Helper\HtmlTreeHelper
        arguments:
          - "@translator.default"
          - "@router"
          - "@request_stack"

    zikula_categories_module.js_tree_helper:
        class: Zikula\CategoriesModule\Helper\JsTreeHelper
        arguments:
          - "@translator.default"
          - "@router"
          - "@request_stack"

    zikula_categories_module.path_builder_helper:
        class: Zikula\CategoriesModule\Helper\PathBuilderHelper
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@zikula_categories_module.api.category"
          - "@zikula_categories_module.relative_category_path_builder_helper"

    zikula_categories_module.relative_category_path_builder_helper:
        class: Zikula\CategoriesModule\Helper\RelativeCategoryPathBuilderHelper
