System:
    installed: 1
    temp: ztemp
    datadir: userdata
    prefix: ''
    development: 1
    system.chmod_dir: 511
    Z_CONFIG_USE_OBJECT_ATTRIBUTION: 0
    Z_CONFIG_USE_OBJECT_CATEGORIZATION: 1
    Z_CONFIG_USE_OBJECT_LOGGING: 0
    Z_CONFIG_USE_OBJECT_META: 0
    Z_CONFIG_USE_TRANSACTIONS: 0
    dbcache.enable: 1
    dbcache.type: Array
    dbcache.servers: none
    dbcache.compression: 1
    dbcache.cache_result: 0
    dbcache.cache_result_ttl: 30
DBInfo:
    databases: { default: { host: localhost, user: root, password: root, dbname: zikula_1_4, dbdriver: mysql, dbtabletype: myisam, charset: utf8, collate: utf8_general_ci } }
Debug:
    error_reporting_development: 30719
    error_reporting_production: 30709
    debug_key: 30719
Log:
    log_dest: FILE
    log_dir: ztemp/error_logs/
    log_file: ztemp/error_logs/zikula-%s.log
    log_file_uid: 0
    log_file_date_format: Ymd
    log_date_format: 'Y-m-d H:i:s'
    log_level_dest: { DB: PRINT }
    log_level_files: { DB: ztemp/error_logs/zikula-sql-%s.log }
    log.apache_uname: 0
    log.enabled: 1
    log.to_display: 1
    log.display_level: 4
    log.display_ajax_level: 4
    log.to_file: 0
    log.file_level: 5
    log.show_php_errorhandler: 1
    log.display_template: 0
    log.to_debug_toolbar: 0
    log.to_debug_toolbar_output: 0
    log.to_debug_toolbar_seckey: ''
    log.sql.to_display: 0
    log.sql.to_file: 0
    debug.display_pagerendertime: 0
Multisites:
    multisites.enabled: 0
    protected.systemvars: {  }