parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     zikula_1_4
    database_user:     zikula_1_4
    database_password: Micro04$#@!

#    mailer_transport:  smtp
#    mailer_host:       localhost
#    mailer_user:       ~
#    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
