#imports:
#    - { resource: config.yml }

parameters:
    mailer_transport: smtp
    mailer_host:      localhost
    mailer_user:      ~
    mailer_password:  ~

    locale: en
    kernel.default_locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
