##
# ZikulaDefaultTheme variables
##
home_template:
  default_value: 3col_w_centerblock
  type: 'Symfony\Component\Form\Extension\Default\Type\ChoiceType'
  options:
    label: 'Template for home page'
    choices:
      'One column': 1col
      'Two columns': 2col
      'Two columns with centerblock': 2col_w_centerblock
      'Three columns': 3col
      'Three columns with centerblock': 3col_w_centerblock
master_template:
  default_value: 2col
  type: 'Symfony\Component\Form\Extension\Default\Type\ChoiceType'
  options:
    label: 'Template for front-end pages'
    choices:
      'One column': 1col
      'Two columns': 2col
      'Two columns with centerblock': 2col_w_centerblock
      'Three columns': 3col
      'Three columns with centerblock': 3col_w_centerblock
admin_template:
  default_value: 1col
  type: 'Symfony\Component\Form\Extension\Default\Type\ChoiceType'
  options:
    label: 'Template for admin area'
    choices:
      'One column': 1col
      'Two columns': 2col
      'Two columns with centerblock': 2col_w_centerblock
      'Three columns': 3col
      'Three columns with centerblock': 3col_w_centerblock
theme_style:
  default_value: cerulean
  type: 'Symfony\Component\Form\Extension\Default\Type\ChoiceType'
  options:
    label: 'Theme style'
    choices:
      'Default': default
      'Cerulean': cerulean
      'Cosmo': cosmo
      'Cyborg': cyborg
      'Darkly': darkly
      'Flatly': flatly
      'Journal': journal
      'Litera': litera
      'Lumen': lumen
      'Lux': lux
      'Materia': materia
      'Minty': minty
      'Pulse': pulse
      'Sandstone': sandstone
      'Simplex': simplex
      'Sketchy': sketchy
      'Slate': slate
      'Solar': solar
      'Spacelab': spacelab
      'Superhero': superhero
      'United': united
      'Yeti': yeti
allow_style_change:
  default_value: false
  type: 'Symfony\Component\Form\Extension\Default\Type\CheckboxType'
  options:
    label: 'Allow users switching the theme style'
    label_attr:
      class: switch-custom
    required: false
    help: 'Enabling this shows a select dropdown in the page footer'
