services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zikula\CoreBundle\Translation\Extractor\Visitor\Php\Zikula\FormTypeAlert:
        tags:
            - { name: php_translation.visitor, type: php }

    Zikula\CoreBundle\Translation\Extractor\Visitor\Php\Zikula\FormTypeInputGroup:
        tags:
            - { name: php_translation.visitor, type: php }
