services:
    zikula_zauth_module.helper.administration_actions_helper:
        class: Zikula\ZAuthModule\Helper\AdministrationActionsHelper
        arguments:
            - "@zikula_permissions_module.api.permission"
            - "@router"
            - "@translator.default"
            - "@zikula_zauth_module.user_verification_repository"
            - "@zikula_users_module.user_repository"

    zikula_zauth_module.helper.file_io:
        class: Zikula\ZAuthModule\Helper\FileIOHelper
        lazy: true
        arguments:
            - "@zikula_extensions_module.api.variable"
            - "@zikula_permissions_module.api.permission"
            - "@translator.default"
            - "@validator"
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_zauth_module.helper.mail_helper"
            - "@event_dispatcher"
            - "@zikula_users_module.current_user"
            - "@zikula_zauth_module.api.password"

    zikula_zauth_module.helper.lost_password_verification_helper:
        class: Zikula\ZAuthModule\Helper\LostPasswordVerificationHelper
        lazy: true
        arguments:
            - "@zikula_zauth_module.user_verification_repository"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_zauth_module.api.password"

    zikula_zauth_module.helper.registration_verification_helper:
        class: Zikula\ZAuthModule\Helper\RegistrationVerificationHelper
        lazy: true
        arguments:
            - "@zikula_permissions_module.api.permission"
            - "@zikula_zauth_module.user_verification_repository"
            - "@zikula_zauth_module.helper.mail_helper"
            - "@zikula_users_module.current_user"
            - "@zikula_users_module.user_repository"
            - "@zikula_zauth_module.api.password"

    zikula_zauth_module.helper.mail_helper:
        class: Zikula\ZAuthModule\Helper\MailHelper
        lazy: true
        arguments:
            - "@translator.default"
            - "@twig"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_mailer_module.api.mailer"

    zikula_zauth_module.helper.migration_helper:
        class: Zikula\ZAuthModule\Helper\MigrationHelper
        deprecated: The "%service_id%" service is deprecated and will be removed in 2.0.
        lazy: true
        arguments:
          - "@zikula_users_module.user_repository"
          - "@doctrine.orm.default_entity_manager"
          - "@validator"
          - "@logger"
