services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $installed: '%env(ZIKULA_INSTALLED)%'

    # alias interface to doctrine service
    Doctrine\Persistence\ManagerRegistry: '@doctrine'

    Zikula\Bundle\CoreBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\Bundle\CoreBundle\Api\ApiInterface\LocaleApiInterface: '@Zikula\Bundle\CoreBundle\Api\LocaleApi'

    Zikula\Bundle\CoreBundle\HttpKernel\ZikulaHttpKernelInterface: '@kernel'

    Zikula\Bundle\CoreBundle\DataCollector\ZikulaVersionDataCollector:
        tags:
            - { name: data_collector, template: '@Core/Collector/zikulaVersion.html.twig', id: 'zikula_version', priority: 300 }

    Zikula\Bundle\CoreBundle\CacheClearer:
        arguments:
          $warmer: '@cache_warmer'
          $fosJsRoutesExtractor: '@fos_js_routing.extractor'
          $cacheDir: '%kernel.cache_dir%'
          $kernelContainerClass: '%kernel.container_class%'

    Zikula\Bundle\CoreBundle\EventListener\BlameListener:
        arguments:
          $blameableListener: '@stof_doctrine_extensions.listener.blameable'

    Zikula\Bundle\CoreBundle\EventListener\ClickjackProtectionListener:
        arguments:
            $xFrameOptions: 'SAMEORIGIN'

    Zikula\Bundle\CoreBundle\EventListener\SiteOffVetoLoginListener:
        lazy: true

    Zikula\Bundle\CoreBundle\EventListener\LoggableListener:
        arguments:
          $loggableListener: '@stof_doctrine_extensions.listener.loggable'

    Zikula\Bundle\CoreBundle\Site\SiteDefinition:
        arguments:
          $defaultLocale: '%kernel.default_locale%'
          $pageVars: '@zikula_core.common.theme.pagevars'

    Symfony\Component\HttpKernel\Fragment\FragmentHandler: '@fragment.handler'
