services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zikula\Bundle\CoreBundle\Translation\Extractor\Visitor\Php\Zikula\FormTypeAlert:
        tags:
            - { name: php_translation.visitor, type: php }

    Zikula\Bundle\CoreBundle\Translation\Extractor\Visitor\Php\Zikula\FormTypeInputGroup:
        tags:
            - { name: php_translation.visitor, type: php }

    Zikula\Bundle\CoreBundle\Translation\Extractor\Visitor\Php\Routes\ZikulaRouteTranslationExtractor:
        tags:
            - { name: php_translation.visitor, type: php }

    Zikula\Bundle\CoreBundle\Command\TranslationKeyToValueCommand:
        arguments:
            $defaultTransPath: '%translator.default_path%'
