<?php
/**
 * Routes.
 *
 * @copyright Zikula contributors (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula contributors <support@zikula.org>.
 * @link http://www.zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace Zikula\RoutesModule\Container\Base;

use Symfony\Component\Routing\RouterInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\Core\Doctrine\EntityAccess;
use Zikula\Core\LinkContainer\LinkContainerInterface;
use Zikula\PermissionsModule\Api\PermissionApi;
use Zikula\UsersModule\Api\CurrentUserApi;
use Zikula\RoutesModule\Entity\RouteEntity;
use Zikula\RoutesModule\Helper\ControllerHelper;

/**
 * This is the link container service implementation class.
 */
class LinkContainer implements LinkContainerInterface
{
    use TranslatorTrait;

    /**
     * @var RouterInterface
     */
    protected $router;

    /**
     * @var PermissionApi
     */
    protected $permissionApi;

    /**
     * @var ControllerHelper
     */
    protected $controllerHelper;

    /**
     * @var CurrentUserApi
     */
    private $currentUserApi;

    /**
     * Constructor.
     * Initialises member vars.
     *
     * @param TranslatorInterface $translator       Translator service instance
     * @param Routerinterface     $router           Router service instance
     * @param PermissionApi       $permissionApi    PermissionApi service instance
     * @param ControllerHelper    $controllerHelper ControllerHelper service instance
     * @param CurrentUserApi      $currentUserApi   CurrentUserApi service instance
     */
    public function __construct(TranslatorInterface $translator, RouterInterface $router, PermissionApi $permissionApi, ControllerHelper $controllerHelper, CurrentUserApi $currentUserApi)
    {
        $this->setTranslator($translator);
        $this->router = $router;
        $this->permissionApi = $permissionApi;
        $this->controllerHelper = $controllerHelper;
        $this->currentUserApi = $currentUserApi;
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * Returns available header links.
     *
     * @param string $type The type to collect links for
     *
     * @return array Array of header links
     */
    public function getLinks($type = LinkContainerInterface::TYPE_ADMIN)
    {
        $utilArgs = ['api' => 'linkContainer', 'action' => 'getLinks'];
        $allowedObjectTypes = $this->controllerHelper->getObjectTypes('api', $utilArgs);

        $permLevel = LinkContainerInterface::TYPE_ADMIN == $type ? ACCESS_ADMIN : ACCESS_READ;

        // Create an array of links to return
        $links = [];

        
        if (LinkContainerInterface::TYPE_ADMIN == $type) {
            
            if (in_array('route', $allowedObjectTypes)
                && $this->permissionApi->hasPermission($this->getBundleName() . ':Route:', '::', $permLevel)) {
                $links[] = [
                    'url' => $this->router->generate('zikularoutesmodule_route_adminview'),
                     'text' => $this->__('Routes'),
                     'title' => $this->__('Route list')
                 ];
            }
        }

        return $links;
    }

    /**
     * Returns action links for a given entity.
     *
     * @param EntityAccess $entity  The entity
     * @param string       $area    The context area name (e.g. admin or nothing for user)
     * @param string       $context The context page name (e.g. view, display, edit, delete)
     *
     * @return array Array of action links
     */
    public function getActionLinks(EntityAccess $entity, $area = '', $context = 'view')
    {
        // Create an array of links to return
        $links = [];

        
        $currentLegacyControllerType = $area != '' ? $area : 'user';
        $currentFunc = $context;
        
        if ($entity instanceof RouteEntity) {
            $component = 'ZikulaRoutesModule:Route:';
            $instance = $this->id . '::';
        
        if ($currentLegacyControllerType == 'admin') {
            if (in_array($currentFunc, ['index', 'view'])) {
                $links[] = [
                    'url' => $this->router->generate('zikularoutesmodule_route_admindisplay', ['id' => $this['id']]),
                    'icon' => 'eye',
                    'linkTitle' => str_replace('"', '', $entity->getTitleFromDisplayPattern()),
                    'linkText' => $this->__('Details')
                ];
            }
            if (in_array($currentFunc, ['index', 'view', 'display'])) {
                if ($this->permissionApi->hasPermission($component, $instance, ACCESS_EDIT)) {
                    $links[] = [
                        'url' => $this->router->generate('zikularoutesmodule_route_adminedit', ['id' => $this['id']]),
                        'icon' => 'pencil-square-o',
                        'linkTitle' => $this->__('Edit'),
                        'linkText' => $this->__('Edit')
                    ];
                    $links[] = [
                        'url' => $this->router->generate('zikularoutesmodule_route_adminedit', ['astemplate' => $this['id']]),
                        'icon' => 'files-o',
                        'linkTitle' => $this->__('Reuse for new item'),
                        'linkText' => $this->__('Reuse')
                    ];
                }
                if ($this->permissionApi->hasPermission($component, $instance, ACCESS_DELETE)) {
                    $links[] = [
                        'url' => $this->router->generate('zikularoutesmodule_route_admindelete', ['id' => $this['id']]),
                        'icon' => 'trash-o',
                        'linkTitle' => $this->__('Delete'),
                        'linkText' => $this->__('Delete')
                    ];
                }
            }
            if ($currentFunc == 'display') {
                $links[] = [
                    'url' => $this->router->generate('zikularoutesmodule_route_adminview'),
                    'icon' => 'reply',
                    'linkTitle' => $this->__('Back to overview'),
                    'linkText' => $this->__('Back to overview')
                ];
            }
        }
        }

        return $links;
    }

    /**
     * Returns the name of the providing bundle.
     *
     * @return string The bundle name
     */
    public function getBundleName()
    {
        return 'ZikulaRoutesModule';
    }
}
