services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zikula\PermissionsBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\PermissionsBundle\Helper\:
        resource: '../../Helper/*'
        lazy: true

    Zikula\PermissionsBundle\Api\ApiInterface\PermissionApiInterface: '@Zikula\PermissionsBundle\Api\PermissionApi'

    Zikula\PermissionsBundle\EventListener\AccessDeniedExceptionListener:
        arguments:
            $installed: '%env(ZIKULA_INSTALLED)%'
        tags:
            - { name: monolog.logger, channel: request }

    Zikula\PermissionsBundle\Menu\MenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createAdminActionsMenu, alias: zikulaPermissionsAdminActionsMenu }

    Zikula\PermissionsBundle\Repository\PermissionRepositoryInterface: '@Zikula\PermissionsBundle\Repository\PermissionRepository'
