language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: 7.1
    - php: hhvm

services:
  - mysql

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then (pecl install -f memcached-2.1.0 && echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini) || echo "Let's continue without memcache extension"; fi;
    # - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php -i; fi;
    # Set the COMPOSER_ROOT_VERSION to the right version according to the branch being built
    - if [ "$TRAVIS_BRANCH" = "master" ]; then export COMPOSER_ROOT_VERSION=dev-master; else export COMPOSER_ROOT_VERSION="$TRAVIS_BRANCH".x-dev; fi;
    - composer self-update
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - mysql -e 'create database zk_test;'

install:
    - composer install
    - zip -qr ZikulaRoutesModule.zip .
    # - wget https://github.com/zikula/core/releases/download/1.4.3/Zikula_Core-1.4.3.build183.tar.gz
    - wget http://ci.zikula.org/job/Zikula_Core-1.4.4/13/artifact/build/archive/Zikula_Core-1.4.4.build13.tar.gz
    - tar -xpzf Zikula_Core-1.4.4.build13.tar.gz
    - rm Zikula_Core-1.4.4.build13.tar.gz
    - cd Zikula_Core-1.4.4
    - php app/console zikula:install:start -n --database_user=root --database_name=zk_test --password=12345678 --email=admin@example.com --router:request_context:host=localhost
    - php app/console zikula:install:finish
    - cd modules
    - mkdir zikula
    - cd zikula
    - mkdir routes-module
    - cd routes-module
    - unzip -q ../../../../ZikulaRoutesModule
    - cd  ../../..
    - php app/console bootstrap:bundles
    - mysql -e "INSERT INTO zk_test.modules (id, name, type, displayname, url, description, directory, version, capabilities, state, securityschema, core_min, core_max) VALUES (NULL, 'ZikulaRoutesModule', '3', 'Routes', 'routes', 'ZikulaRoutesModule module generated by ModuleStudio 0.7.0.', 'zikula/routes-module', '1.1.0', 'N;', '3', 'N;', '1.4.4', '2.0.0');"
    - php app/console cache:warmup

script:
    - php app/console lint:yaml modules/zikula/routes-module/Resources
    - php app/console lint:twig @ZikulaRoutesModule
    - phpunit --configuration modules/zikula/routes-module/phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover -v

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

before_deploy:
    - cd ..
    - mkdir release
    - cd release
    - unzip -q ../ZikulaRoutesModule.zip
    - rm -Rf vendor
    - rm -Rf .git
    - composer install --no-dev --prefer-dist
    - rm auth.json
    - zip -qr ZikulaRoutesModule.zip .

deploy:
  provider: releases
  api_key:
    secure: "" # Enter your api key here!
  file: ZikulaRoutesModule.zip
  on:
    tags: true
    repo: zikula/RoutesModule

