<?php
/**
 * Routes.
 *
 * @copyright Zikula contributors (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula contributors <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\RoutesModule;

use Zikula\RoutesModule\Base\AbstractZikulaRoutesModule;

/**
 * Module implementation class.
 */
class ZikulaRoutesModule extends AbstractZikulaRoutesModule
{
    // custom enhancements can go here
}
