services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\RoutesBundle\ZikulaRoutesBundle'

    Zikula\RoutesBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Base/bootstrap.php,Tests,vendor}'

    Zikula\RoutesBundle\Helper\:
        resource: '../../Helper/*'
        lazy: true

    Zikula\RoutesBundle\Helper\RouteDumperHelper:
        arguments:
            $dumpCommand: '@fos_js_routing.dump_command'
