services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\MenuModule\ZikulaMenuModule'

    Zikula\MenuModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\MenuModule\Voter\RequestVoter:
        tags: ['knp_menu.voter']
