translation:
    # extend the debug profiler with information about requests.
    symfony_profiler:
        # https://php-translation.readthedocs.io/en/latest/symfony/profiler-ui.html
        # turn the symfony profiler integration on or off. Defaults to kernel debug mode.
        enabled: true
        #formatter: null

        # Limit long HTTP message bodies to x characters. If set to 0 we do not read the message body.
        # Only available with the default formatter (FullHttpMessageFormatter).
        #captured_body_length: 0

        allow_edit: true

    # automatically add missing translations
    auto_add_missing_translations:
        # https://php-translation.readthedocs.io/en/latest/symfony/auto-add-missing.html
        enabled: false
        config_name: zikula # the configuration to use

    webui:
        enabled: true
        allow_create: true
        allow_delete: true
