services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zikula\ExtensionsBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\ExtensionsBundle\Api\ApiInterface\CapabilityApiInterface: '@Zikula\ExtensionsBundle\Api\CapabilityApi'
