services:
    zikula_users_module.user_repository:
        class: Zikula\UsersModule\Entity\Repository\UserRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ["ZikulaUsersModule:UserEntity"]

    zikula_users_module.user_session_repository:
        class: Zikula\UsersModule\Entity\Repository\UserSessionRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ["ZikulaUsersModule:UserSessionEntity"]

    zikula_users_module.user_attribute_repository:
        class: Zikula\UsersModule\Entity\Repository\UserAttributeRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ["ZikulaUsersModule:UserAttributeEntity"]
