services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $bundle: '@Zikula\UsersModule\ZikulaUsersModule'

    Zikula\UsersModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\UsersModule\Helper\:
        resource: '../../Helper/*'
        lazy: true

    Zikula\UsersModule\Api\ApiInterface\CurrentUserApiInterface: '@Zikula\UsersModule\Api\CurrentUserApi'
    Zikula\UsersModule\Entity\RepositoryInterface\UserAttributeRepositoryInterface: '@Zikula\UsersModule\Entity\Repository\UserAttributeRepository'
    Zikula\UsersModule\Entity\RepositoryInterface\UserRepositoryInterface: '@Zikula\UsersModule\Entity\Repository\UserRepository'
    Zikula\UsersModule\Entity\RepositoryInterface\UserSessionRepositoryInterface: '@Zikula\UsersModule\Entity\Repository\UserSessionRepository'

    # public because installer accesses this using container
    Zikula\UsersModule\Entity\Repository\UserRepository:
        public: true

    # public because this is often required as part of Doctrine listeners
    # which need to access this using container because CurrentUserApi
    # depends on entities as well
    Zikula\UsersModule\Api\CurrentUserApi:
        public: true

    Zikula\UsersModule\Collector\AuthenticationMethodCollector:
        arguments:
          $methods: !tagged_iterator zikula.authentication_method

    Zikula\UsersModule\Collector\MessageModuleCollector:
        arguments:
          $modules: !tagged_iterator zikula.message_module

    Zikula\UsersModule\Collector\ProfileModuleCollector:
        arguments:
          $modules: !tagged_iterator zikula.profile_module
