<?php

declare(strict_types=1);

/**
 * Routes.
 *
 * @copyright Zikula contributors (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula contributors <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\RoutesModule\Validator\Constraints;

use Zikula\RoutesModule\Validator\Constraints\Base\AbstractListEntry;

/**
 * List entry validation constraint.
 *
 * @Annotation
 */
class ListEntry extends AbstractListEntry
{
    // here you can customise the constraint
}
