services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\AdminModule\ZikulaAdminModule'

    Zikula\AdminModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\AdminModule\Helper\:
        resource: '../../Helper/*'
        lazy: true
