services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $bundle: '@Zikula\AdminModule\ZikulaAdminModule'

    Zikula\AdminModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\AdminModule\Helper\:
        resource: '../../Helper/*'
        lazy: true

    Zikula\AdminModule\Entity\RepositoryInterface\AdminCategoryRepositoryInterface: '@Zikula\AdminModule\Entity\Repository\AdminCategoryRepository'
    Zikula\AdminModule\Entity\RepositoryInterface\AdminModuleRepositoryInterface: '@Zikula\AdminModule\Entity\Repository\AdminModuleRepository'

    Zikula\AdminModule\Listener\ModuleEventListener:
        arguments:
          $installed: '%installed%'
