#!/usr/bin/env php
<?php

use Zikula\Bundle\CoreBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

set_time_limit(0);

$loader = require __DIR__.'/../vendor/autoload.php';
require_once __DIR__.'/ZikulaKernel.php';

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

$kernel = new ZikulaKernel($env, $debug);
$kernel->setAutoloader($loader);
$application = new Application($kernel);
$application->run($input);
