#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;
use Zikula\Bundle\CoreBundle\Yaml\Yaml;
use Zikula\Bundle\CoreBundle\Console\Application;

set_time_limit(0);

require __DIR__.'/autoload.php';
require __DIR__.'/ZikulaKernel.php';
require __DIR__.'/../lib/requirementCheck.php';

$getZikulaEnv = function(ArgvInput $input) {
    $defaultEnv = $input->getParameterOption(['--env', '-e'], getenv('ZIKULA_ENV') ?: 'dev');
    // prefer install and upgrade commands default to prod environment
    $isInstallUpgradeCommand = ((strpos($input->getFirstArgument(), 'zikula:install') !== false)
        || (strpos($input->getFirstArgument(), 'zikula:upgrade') !== false));
    $env = $isInstallUpgradeCommand ? 'prod' : $defaultEnv;
    return $env;
};

$input = new ArgvInput();
$env = $getZikulaEnv($input);
$debug = getenv('ZIKULA_DEBUG') !== '0' && !$input->hasParameterOption(['--no-debug', '']) && 'prod' !== $env;

if ($debug) {
    Debug::enable();
}

// on install or upgrade, check if system requirements are met.
$kernelConfig = Yaml::parse(file_get_contents(__DIR__.'/config/parameters.yml'));
if (is_readable($file = __DIR__.'/config/custom_parameters.yml')) {
    $kernelConfig = array_merge($kernelConfig, Yaml::parse(file_get_contents($file)));
}
requirementCheck($kernelConfig['parameters']);

$kernel = new ZikulaKernel($env, $debug);
$kernel->boot();

$application = new Application($kernel);
$application->run($input);
