imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    # keep profiler enabled because some tests may fail
    # when container can not be compiled
    # because a controller injects the Profiler class
    #profiler:
    #    enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
