core:
    resource: "@CoreBundle/Resources/config/routing.xml"

hook:
    resource: "@ZikulaHookBundle/Resources/config/routing.yaml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

installer:
    resource: "@ZikulaCoreInstallerBundle/Resources/config/routing/routing.xml"

workflow_editor:
    resource: "@ZikulaWorkflowBundle/Resources/config/routing.yaml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

_translation:
    resource: routes/php_translation.yaml

# Note: if you want to add routes for a native Symfony bundle
# insert them here and not below the "Routing" entry

Routing:
    resource: .
    type: zikularoutesmodule
