<?php

declare(strict_types=1);

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Zikula\Bundle\CoreBundle\CoreBundle::class => ['all' => true],
    Zikula\Bundle\FormExtensionBundle\ZikulaFormExtensionBundle::class => ['all' => true],
    Zikula\SettingsBundle\ZikulaSettingsBundle::class => ['all' => true],
    JMS\I18nRoutingBundle\JMSI18nRoutingBundle::class => ['all' => true],
    Zikula\RoutesBundle\ZikulaRoutesBundle::class => ['all' => true],
    FOS\JsRoutingBundle\FOSJsRoutingBundle::class => ['all' => true],
    Matthias\SymfonyConsoleForm\Bundle\SymfonyConsoleFormBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Liip\ImagineBundle\LiipImagineBundle::class => ['all' => true],
    Translation\Bundle\TranslationBundle::class => ['all' => true],
    Bazinga\Bundle\JsTranslationBundle\BazingaJsTranslationBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Oro\TwigInspector\Bundle\OroTwigInspectorBundle::class => ['dev' => true],
    Zikula\AdminBundle\ZikulaAdminBundle::class => ['all' => true],
    Zikula\CategoriesBundle\ZikulaCategoriesBundle::class => ['all' => true],
    Zikula\ExtensionsBundle\ZikulaExtensionsBundle::class => ['all' => true],
    Zikula\GroupsBundle\ZikulaGroupsBundle::class => ['all' => true],
    Zikula\LegalBundle\ZikulaLegalBundle::class => ['all' => true],
    Zikula\MenuBundle\ZikulaMenuBundle::class => ['all' => true],
    Zikula\PermissionsBundle\ZikulaPermissionsBundle::class => ['all' => true],
    Zikula\ProfileBundle\ZikulaProfileBundle::class => ['all' => true],
    Zikula\SecurityCenterBundle\ZikulaSecurityCenterBundle::class => ['all' => true],
    Zikula\StaticContentBundle\ZikulaStaticContentBundle::class => ['all' => true],
    Zikula\ThemeBundle\ZikulaThemeBundle::class => ['all' => true],
    Zikula\UsersBundle\ZikulaUsersBundle::class => ['all' => true],
    Zikula\ZAuthBundle\ZikulaZAuthBundle::class => ['all' => true],
    Zikula\DefaultThemeBundle\ZikulaDefaultThemeBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
];
