_framework:
    resource: routes/dev/framework.yaml

_profiler:
    resource: routes/dev/web_profiler.yaml

_translation:
    resource: routes/dev/php_translation.yaml

_main:
    resource: routing.yaml
