services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\SecurityCenterModule\ZikulaSecurityCenterModule'
            $installed: '%env(ZIKULA_INSTALLED)%'
            $isUpgrading: "@=container.hasParameter('upgrading') ? parameter('upgrading') : false"
            $projectDir: '%kernel.project_dir%'

    Zikula\SecurityCenterModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\SecurityCenterModule\Helper\:
        resource: '../../Helper/*'
        lazy: true

    Zikula\SecurityCenterModule\Api\ApiInterface\HtmlFilterApiInterface: '@Zikula\SecurityCenterModule\Api\HtmlFilterApi'

    Zikula\SecurityCenterModule\Listener\FilterListener:
        arguments:
          $cacheDir: '%kernel.cache_dir%'

    Zikula\SecurityCenterModule\Listener\ClickjackProtectionListener:
        arguments:
            $xFrameOptions: 'SAMEORIGIN'
