services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\SecurityCenterBundle\ZikulaSecurityCenterBundle'
            $installed: '%env(ZIKULA_INSTALLED)%'
            $isUpgrading: "@=container.hasParameter('upgrading') ? parameter('upgrading') : false"
            $projectDir: '%kernel.project_dir%'

    Zikula\SecurityCenterBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\SecurityCenterBundle\Helper\:
        resource: '../../Helper/*'
        lazy: true

    Zikula\SecurityCenterBundle\Api\ApiInterface\HtmlFilterApiInterface: '@Zikula\SecurityCenterBundle\Api\HtmlFilterApi'

    Zikula\SecurityCenterBundle\Listener\ClickjackProtectionListener:
        arguments:
            $xFrameOptions: 'SAMEORIGIN'
