services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zikula\ThemeBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\ThemeBundle\Bundle\MetaData\ThemeBundleMetaData:
        public: true

    Zikula\ThemeBundle\Helper\:
        resource: '../../Helper/*'
        lazy: true
