services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zikula\ThemeBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\ThemeBundle\EventSubscriber\CreateThemedResponseSubscriber:
        tags:
            - { name: monolog.logger, channel: request }

    Zikula\ThemeBundle\EventSubscriber\ControllerAnnotationReaderSubscriber:
        tags:
            - { name: monolog.logger, channel: request }

    Zikula\ThemeBundle\Helper\:
        resource: '../../Helper/*'
        lazy: true
