parameters:
    zikula_routes_module.console_command_listener.class: Zikula\RoutesModule\Translation\ConsoleCommandListener
    zikula_routes_module.route_dumper_helper.class: Zikula\RoutesModule\Helper\RouteDumperHelper
    jms_i18n_routing.route_exclusion_strategy.class: Zikula\RoutesModule\Translation\DefaultRouteExclusionStrategy
    jms_i18n_routing.pattern_generation_strategy.class: Zikula\RoutesModule\Translation\ZikulaPatternGenerationStrategy
    jms_i18n_routing.route_translation_extractor.class: Zikula\RoutesModule\Translation\ZikulaRouteTranslationExtractor

services:
    zikula_routes_module.routing_finder:
        class: Zikula\RoutesModule\Routing\RouteFinder

    zikula_routes_module.route_dumper_helper:
        class: "%zikula_routes_module.route_dumper_helper.class%"
        arguments: ["@service_container"]

    zikula_routes_module.console_command_listener:
        class: "%zikula_routes_module.console_command_listener.class%"
        tags:
            - { name: kernel.event_subscriber }

    zikula_routes_module.routing_loader:
        class: Zikula\RoutesModule\Routing\RouteLoader
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@kernel"]
        tags:
            - { name: routing.loader }

    zikula_routes_module.installer_listener:
        class: Zikula\RoutesModule\Listener\InstallerListener
        arguments: ["@doctrine.orm.entity_manager", "@zikula_routes_module.routing_finder", "@zikula.cache_clearer", "@zikula_routes_module.route_dumper_helper", "@zikula_routes_module.multilingual_routing_helper"]
        tags:
            - { name: kernel.event_subscriber }
