parameters:
    jms_i18n_routing.route_exclusion_strategy.class: Zikula\RoutesModule\Translation\DefaultRouteExclusionStrategy
    jms_i18n_routing.pattern_generation_strategy.class: Zikula\RoutesModule\Translation\ZikulaPatternGenerationStrategy
    jms_i18n_routing.route_translation_extractor.class: Zikula\RoutesModule\Translation\ZikulaRouteTranslationExtractor

services:
    jms_i18n_routing.route_exclusion_strategy:
        class: '%jms_i18n_routing.route_exclusion_strategy.class%'
        arguments:
            - "@zikula_routes_module.extract_translation_helper"

    zikula_routes_module.extract_translation_helper:
        class: Zikula\RoutesModule\Helper\ExtractTranslationHelper

    zikula_routes_module.multilingual_routing_helper:
        class: Zikula\RoutesModule\Helper\MultilingualRoutingHelper
        arguments:
            - "@zikula_extensions_module.api.variable"
            - "@zikula.dynamic_config_dumper"
            - "@zikula.cache_clearer"
            - "@zikula_settings_module.locale_api"
            - "@kernel"
            - "%locale%"
            - "%installed%"

    zikula_routes_module.path_builder_helper:
        class: Zikula\RoutesModule\Helper\PathBuilderHelper
        arguments:
            - "@kernel"

    zikula_routes_module.route_dumper_helper:
        class: Zikula\RoutesModule\Helper\RouteDumperHelper
        arguments:
            - "@service_container"

    zikula_routes_module.sanitize_helper:
        class: Zikula\RoutesModule\Helper\SanitizeHelper

    zikula_routes_module.installer_listener:
        class: Zikula\RoutesModule\Listener\InstallerListener
        arguments:
            - "@zikula.cache_clearer"
            - "@zikula_routes_module.route_dumper_helper"
            - "@zikula_routes_module.multilingual_routing_helper"
            - "@zikula_routes_module.entity_factory"
        tags:
            - { name: kernel.event_subscriber }

    zikula_routes_module.routing_loader:
        class: Zikula\RoutesModule\Routing\RouteLoader
        arguments:
            - "@kernel"
            - "@translator"
            - "@zikula_routes_module.entity_factory"
            - "@zikula_routes_module.extract_translation_helper"
            - "@zikula_routes_module.path_builder_helper"
            - "@zikula_routes_module.sanitize_helper"
            - "%locale%"
        tags:
            - { name: routing.loader }

    zikula_routes_module.console_command_listener:
        class: Zikula\RoutesModule\Translation\ConsoleCommandListener
        arguments:
            - "@zikula_routes_module.extract_translation_helper"
        tags:
            - { name: kernel.event_subscriber }
