services:
    # Event subscriber and listener classes
    zikula_routes_module.entity_lifecycle_listener:
        class: Zikula\RoutesModule\Listener\EntityLifecycleListener
        arguments:
            - "@event_dispatcher"
            - "@logger"
        tags:
            - { name: doctrine.event_subscriber }
    
#    zikula_routes_module.kernel_listener:
#        class: Zikula\RoutesModule\Listener\KernelListener
#        tags:
#            - { name: kernel.event_subscriber }
    
#    zikula_routes_module.installer_listener:
#        class: Zikula\RoutesModule\Listener\InstallerListener
#        tags:
#            - { name: kernel.event_subscriber }
    
#    zikula_routes_module.moduledispatch_listener:
#        class: Zikula\RoutesModule\Listener\ModuleDispatchListener
#        tags:
#            - { name: kernel.event_subscriber }
    
#    zikula_routes_module.mailer_listener:
#        class: Zikula\RoutesModule\Listener\MailerListener
#        tags:
#            - { name: kernel.event_subscriber }
    
#    zikula_routes_module.theme_listener:
#        class: Zikula\RoutesModule\Listener\ThemeListener
#        tags:
#            - { name: kernel.event_subscriber }
    
#    zikula_routes_module.userlogin_listener:
#        class: Zikula\RoutesModule\Listener\UserLoginListener
#        tags:
#            - { name: kernel.event_subscriber }
    
#    zikula_routes_module.userlogout_listener:
#        class: Zikula\RoutesModule\Listener\UserLogoutListener
#        tags:
#            - { name: kernel.event_subscriber }
    
#    zikula_routes_module.user_listener:
#        class: Zikula\RoutesModule\Listener\UserListener
#        arguments:
#            - "@translator.default"
#            - "@zikula_routes_module.entity_factory"
#            - "@zikula_users_module.current_user"
#            - "@logger"
#        tags:
#            - { name: kernel.event_subscriber }
    
#    zikula_routes_module.userregistration_listener:
#        class: Zikula\RoutesModule\Listener\UserRegistrationListener
#        tags:
#            - { name: kernel.event_subscriber }
    
#    zikula_routes_module.users_listener:
#        class: Zikula\RoutesModule\Listener\UsersListener
#        tags:
#            - { name: kernel.event_subscriber }
    
#    zikula_routes_module.group_listener:
#        class: Zikula\RoutesModule\Listener\GroupListener
#        tags:
#            - { name: kernel.event_subscriber }
    
