<?php

/**
 * Routes.
 *
 * @copyright Zikula contributors (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula contributors <info@ziku.la>.
 *
 * @see https://ziku.la
 *
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\RoutesModule\Form\Type;

use Zikula\RoutesModule\Form\Type\Base\AbstractConfigType;

/**
 * Configuration form type implementation class.
 */
class ConfigType extends AbstractConfigType
{
    // feel free to extend the base form type class here
}
