parameters:
    zikula_profile_module.property_prefix: 'zpmpp'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zikula\ProfileBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\ProfileBundle\Helper\:
        resource: '../../Helper/*'
        lazy: true

    Zikula\ProfileBundle\EventSubscriber\AttributeNameTranslationSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Zikula\ProfileBundle\Menu\MenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: zikulaProfileAdminMenu }

    Zikula\ProfileBundle\Repository\PropertyRepositoryInterface: '@Zikula\ProfileBundle\Repository\PropertyRepository'
