##
# ZikulaAtomTheme variables
##
showdescription:
  default_value: true
  type: 'Symfony\Component\Form\Extension\Core\Type\CheckboxType'
  options:
    label: 'Show item descriptions'
    label_attr:
      class: switch-custom
    disabled: true
rsslevel:
  default_value: rss20
  type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
  options:
    label: 'RSS Version'
    choices:
      "RSS v0.91": rss091
      "RSS v0.20": rss20
