<?php

/**
 * Routes.
 *
 * @copyright Zikula contributors (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula contributors <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\RoutesModule\DependencyInjection;

use Zikula\RoutesModule\DependencyInjection\Base\AbstractZikulaRoutesExtension;

/**
 * DependencyInjection extension implementation class.
 */
class ZikulaRoutesExtension extends AbstractZikulaRoutesExtension
{
    // custom enhancements can go here
}
