## YAML Override template
## original/file.tpl: override/file.tpl
---
system/SearchModule/Resources/view/search_block_search.tpl: themes/SeaBreezeTheme/Resources/view/modules/Search/search_block_search.tpl
system/BlocksModule/Resources/view/blocks_block_extmenu_topnav.tpl: themes/SeaBreezeTheme/Resources/view/modules/Blocks/blocks_block_extmenu_topnav.tpl