services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\SettingsModule\ZikulaSettingsModule'
            $defaultLocale: '%locale%'
            $installed: '%installed%'

    Zikula\SettingsModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\SettingsModule\Api\ApiInterface\LocaleApiInterface: '@Zikula\SettingsModule\Api\LocaleApi'

    # public because core installer and others accesses this using container
    Zikula\SettingsModule\Api\LocaleApi:
        public: true

    Zikula\SettingsModule\SettingsModuleInstaller:
        arguments:
            $locale: '%locale%'
