services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\SettingsModule\ZikulaSettingsModule'
            $defaultLocale: '%locale%'
            $installed: '%env(ZIKULA_INSTALLED)%'
            $projectDir: '%kernel.project_dir%'

    Zikula\SettingsModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\SettingsModule\Api\ApiInterface\LocaleApiInterface: '@Zikula\SettingsModule\Api\LocaleApi'

    Zikula\SettingsModule\SettingsModuleInstaller:
        arguments:
            $locale: '%locale%'
