<?php
/**
 * Copyright Zikula Foundation 2009 - Zikula Application Framework
 *
 * This work is contributed to the Zikula Foundation under one or more
 * Contributor Agreements and licensed to You under the following license:
 *
 * @license GNU/LGPLv3 (or at your option, any later version).
 * @package Zikula
 *
 * Please see the NOTICE file distributed with this source code for further
 * information regarding copyright and licensing.
 */

class Mailer_Controller_Admin extends Zikula_AbstractController
{
    /**
     * Post initialise.
     *
     * @return void
     */
    protected function postInitialize()
    {
        // In this controller we do not want caching.
        $this->view->setCaching(Zikula_View::CACHE_DISABLED);
    }

    /**
     * the main administration function
     * This function is the default function, and is called whenever the
     * module is initiated without defining arguments.  As such it can
     * be used for a number of things, but most commonly it either just
     * shows the module menu and returns or calls whatever the module
     * designer feels should be the default function (often this is the
     * view() function)
     * @return string HTML string
     */
    public function main()
    {
        // Security check will be done in modifyconfig()
        $this->redirect(ModUtil::url('Mailer', 'admin', 'modifyconfig'));
    }

    /**
     * This is a standard function to modify the configuration parameters of the
     * module
     * @return string HTML string
     */
    public function modifyconfig()
    {
        // security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Mailer::', '::', ACCESS_ADMIN));

        $form = FormUtil::newForm('Mailer', $this);

        return $form->execute('mailer_admin_modifyconfig.tpl', new Mailer_Form_Handler_ModifyConfig());
    }

    /**
     * This function displays a form to sent a test mail
     * @return string HTML string
     */
    public function testconfig()
    {
        // security check
        if (!SecurityUtil::checkPermission('Mailer::', '::', ACCESS_ADMIN)) {
            return LogUtil::registerPermissionError();
        }

        // Return the output that has been generated by this function
        return $this->view->fetch('mailer_admin_testconfig.tpl');
    }

    /**
     * This function processes the results of the test form
     * @param string args['toname '] name to the recipient
     * @param string args['toaddress'] the address of the recipient
     * @param string args['subject'] message subject
     * @param string args['body'] message body
     * @param int args['html'] HTML flag
     * @return bool true
     */
    public function sendmessage($args)
    {
        $this->checkCsrfToken();

        // security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Mailer::', '::', ACCESS_ADMIN));

        $toname = (string)$this->request->request->get('toname');
        $toaddress = (string)$this->request->request->get('toaddress');
        $subject = (string)$this->request->request->get('subject');
        $body = (string)$this->request->request->get('body');
        $altBody = (string)$this->request->request->get('altbody', false);
        $html = (bool)$this->request->request->get('html', false);

        // set the email
        $result = ModUtil::apiFunc('Mailer', 'user', 'sendmessage',
                    array('toname' => $toname,
                    'toaddress' => $toaddress,
                    'subject' => $subject,
                    'body' => $body,
                    'altbody' => $altBody,
                    'html' => $html));

        // check our result and return the correct error code
        if ($result === true) {
            // Success
            LogUtil::registerStatus($this->__('Done! Message sent.'));
        } elseif ($result === false) {
            // Failiure
            LogUtil::registerError($this->__f('Error! Could not send message. %s', ''));
        } else {
            // Failiure with error
            LogUtil::registerError($this->__f('Error! Could not send message. %s', $result));
        }

        // This function generated no output, and so now it is complete we redirect
        // the user to an appropriate page for them to carry on their work
        $this->redirect(ModUtil::url('Mailer', 'admin', 'testconfig'));
    }
}
