services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zikula\DefaultThemeBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\DefaultThemeBundle\EventListener\BootstrapAssetSetterListener:
        arguments:
            $cssAssetBag: '@zikula_core.common.theme.assets_css'

    Zikula\DefaultThemeBundle\Menu\MenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: zikulaDefaultThemeAdminMenu }
