system/zikulaRoutes/Resources/views/Route/index.tpl: config/templates/ZikulaRoutesModule/Route/index.tpl
system/zikulaRoutes/Resources/views/Route/view.tpl: config/templates/ZikulaRoutesModule/Route/view.tpl
system/zikulaRoutes/Resources/views/Route/view_quickNav.tpl: config/templates/ZikulaRoutesModule/Route/view_quickNav.tpl
system/zikulaRoutes/Resources/views/Route/display.tpl: config/templates/ZikulaRoutesModule/Route/display.tpl
system/zikulaRoutes/Resources/views/Route/delete.tpl: config/templates/ZikulaRoutesModule/Route/delete.tpl
system/zikulaRoutes/Resources/views/Route/reload.tpl: config/templates/ZikulaRoutesModule/Route/reload.tpl
system/zikulaRoutes/Resources/views/Route/renew.tpl: config/templates/ZikulaRoutesModule/Route/renew.tpl
system/zikulaRoutes/Resources/views/Admin/header.tpl: config/templates/ZikulaRoutesModule/Admin/header.tpl
system/zikulaRoutes/Resources/views/Admin/footer.tpl: config/templates/ZikulaRoutesModule/Admin/footer.tpl
system/zikulaRoutes/Resources/views/Route/edit.tpl: config/templates/ZikulaRoutesModule/Route/edit.tpl
system/zikulaRoutes/Resources/views/Route/inlineRedirectHandler.tpl: config/templates/ZikulaRoutesModule/Route/inlineRedirectHandler.tpl
system/zikulaRoutes/Resources/views/Helper/include_standardfields_display.tpl: config/templates/ZikulaRoutesModule/Helper/include_standardfields_display.tpl
system/zikulaRoutes/Resources/views/Helper/include_standardfields_edit.tpl: config/templates/ZikulaRoutesModule/Helper/include_standardfields_edit.tpl
system/zikulaRoutes/Resources/views/include_filterSyntaxDialog.tpl: config/templates/ZikulaRoutesModule/include_filterSyntaxDialog.tpl
system/zikulaRoutes/Resources/views/include_pdfheader.tpl: config/templates/ZikulaRoutesModule/include_pdfheader.tpl
