services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $twigLoader: '@twig.loader'

    Zikula\LegalBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\LegalBundle\Bundle\MetaData\LegalBundleMetaData:
        public: true

    Zikula\LegalBundle\Helper\:
        resource: '../../Helper/*'
        lazy: true
